import type { SituationItem } from './api'

// Situations don't have a short title of their own (only a full question
// sentence), so known ids get a hand-picked label here. Anything created
// later via the admin screen falls back to its question text below.
const TITLES: Record<string, string> = {
  'fell-down': '넘어진 친구 돕기',
  birthday: '생일 파티 알아채기',
  'no-umbrella': '우산 없이 비를 맞을 때',
  'toy-fight': '장난감 다툼 해결하기',
  'perfect-score': '시험 잘 봤을 때 기분',
  'group-project': '모둠 과제 갈등',
  gossip: '친구 뒷담화 대처하기',
  'team-sports': '진 팀 친구 위로하기',
  'borrow-item': '빌린 준비물 책임지기',
  bystander: '따돌림 목격했을 때',
  'broken-item': '실수로 물건 망가뜨렸을 때',
  'new-student': '전학생 맞이하기',
  'lost-item': '소중한 물건을 잃어버렸을 때',
  'unfair-blame': '억울하게 오해받았을 때',
  'line-cutting': '새치기 대처하기',
  'not-picked': '편 가르기에서 마지막까지 남았을 때',
  'sibling-turn': '차례 기다리기',
  'compliment-jealousy': '친구가 칭찬받을 때',
  'promise-broken': '약속 어긴 친구 대하기',
  'accidental-hurt': '무심코 한 말로 상처 줬을 때',
  'cheating-on-test': '시험 중 커닝 상황',
  'chat-exclusion': '단체 채팅방 소외',
  'losing-competition': '대회에서 진 친구 위로하기',
  'plagiarism-temptation': '친구 과제 베끼고 싶은 유혹',
  'rumor-spreading': '헛소문이 퍼질 때',
  'class-pet-neglect': '학급 동물 돌봄 소홀',
  'found-money': '길에서 돈을 주웠을 때',
  'exam-stress-friend': '시험 스트레스 받는 친구',
  'sibling-comparison': '형제자매와 비교당할 때',
  'team-blame-game': '경기 진 뒤 친구 탓하기',
  'secret-diary-peek': '친구 일기장을 몰래 봤을 때',
  'language-barrier-student': '말이 서툰 전학생',
  'borrowed-item-broken': '빌린 물건을 망가뜨렸을 때',
  'appearance-teasing-witness': '외모 놀림 목격했을 때',
  'presentation-freeze': '발표 중 머릿속이 하얘질 때',
  'credit-hogging': '모둠 성과 혼자 차지하기',
  'online-mean-comment': '온라인 악플을 받았을 때',
  'unfair-scolding': '억울하게 혼났을 때',
  'wheelchair-friend-inclusion': '몸이 불편한 친구와 함께 놀기',
  'littering-witness': '쓰레기 무단 투기 목격',
  'spilled-paint-artclass': '물감 쏟은 짝꿍 돕기',
  'library-shelf-help': '도서관에서 책 찾는 친구 돕기',
  'swing-cutting-line': '그네 순서 새치기 대처하기',
  'picky-eater-teasing': '편식한다고 놀림당하는 친구',
  'pool-water-fear': '물 무서워하는 친구 응원하기',
  'heavy-backpack-help': '무거운 가방 든 친구 돕기',
  'science-experiment-mistake': '실험 실수한 친구 감싸기',
  'off-key-singing-tease': '음정 틀렸다고 놀림당할 때',
  'dodgeball-selfblame': '피구에서 자책하는 친구 위로하기',
  'academy-bus-seat': '버스에서 자리 양보하기',
  'stationery-store-mischarge': '거스름돈 더 받았을 때',
  'amusement-park-scared-sibling': '놀이기구 무서워하는 동생',
  'camping-tent-teamwork': '캠핑장 텐트 함께 정리하기',
  'reading-room-noise': '독서실에서 떠드는 친구',
  'classroom-cleanup-alone': '혼자 남아 청소하는 친구 돕기',
  'bus-stop-rain-grandma': '비 맞는 할머니께 우산 나눠드리기',
  'museum-touching-artwork': '전시 작품 함부로 만지려 할 때',
  'soccer-foul-forgive': '반칙한 상대 팀 용서하기',
  'sandcastle-destroyed': '모래성 무너뜨렸을 때 사과하기',
  'classroom-meeting-ignored': '학급 회의에서 의견 무시당할 때',
  'online-game-blame': '온라인 게임에서 팀원 탓하기',
  'choir-practice-teasing': '합창 연습에서 음 놓쳐 놀림당할 때',
  'volunteer-giving-up': '봉사활동 힘들어하는 친구 격려하기',
  'new-student-welcome-party': '전학생 환영 파티 준비하기',
  'field-trip-room-assignment': '수학여행 방 배정 갈등',
  'vet-waiting-room-comfort': '동물병원에서 우는 동생 위로하기',
  'salon-cutting-line': '미용실에서 새치기 목격하기',
  'seesaw-weight-exclusion': '몸무게 차이로 시소 놀이 소외',
  'school-garden-watering': '텃밭 물주기 깜빡했을 때',
  'lunch-line-junior-cutting': '급식 줄 새치기하는 후배',
  'school-play-forgotten-line': '학예회에서 대사 잊은 친구 돕기',
  'afterschool-alone-classroom': '방과후 혼자 남은 친구',
  'stairs-junior-fall': '계단에서 넘어진 동생 돕기',
  'stationery-share-refused': '연필 빌려주기 거절당했을 때',
  'tag-game-rule-breaking': '술래잡기 규칙 어기는 친구',
  'allergy-food-consideration': '알레르기 있는 친구 배려하기',
  'fieldtrip-busmotionsick': '체험학습 버스에서 멀미하는 친구',
  'dogwalk-turn-conflict': '반려견 산책 순서 다투기',
  'festival-booth-empty': '축제 부스에 손님이 없을 때',
  'invention-idea-suspicion': '발명품 아이디어 비슷해서 의심될 때',
  'online-class-mic-mistake': '온라인 수업 마이크 실수',
  'playground-bike-not-yielding': '자전거 양보 안 하는 친구',
  'class-library-book-damage': '학급문고 책 찢고 숨기기',
  'taekwondo-belt-test-fail': '승급 심사 떨어진 친구 위로하기',
  'playground-shade-exhausted': '더위에 지친 친구 챙기기',
  'schoolstore-no-money': '매점에서 돈 없는 친구 배려하기',
  'quiz-contest-wrong-answer': '퀴즈대회에서 오답 낸 친구',
  'art-exhibit-low-score': '미술 전시 낮은 평가에 실망한 친구',
  'relay-race-baton-drop': '이어달리기 배턴 놓친 친구',
  'winter-camp-homesick': '캠프에서 향수병 걸린 친구',
  'jungle-gym-turn-pushed': '정글짐 순서에서 밀려난 친구',
  'lunchroom-tray-mess': '식판 정리 안 하고 가는 친구',
  'math-class-crying': '수학 문제 못 풀어 우는 친구',
  'art-show-missing-work': '전시 작품이 사라졌을 때',
  'stationery-shop-theft-witness': '문구점에서 훔치는 걸 목격했을 때',
  'playground-dog-fear': '강아지 무서워하는 친구 달래기',
  'new-cook-greeting': '새로 오신 조리사님께 인사하기',
  'library-adult-phonecall': '도서관에서 큰 소리로 통화하는 어른',
  'tug-of-war-weak-teasing': '줄다리기에서 진 친구 탓하기',
  'art-class-sharing-paper': '색종이 부족한 친구와 나누기',
  'online-class-camera-off': '온라인 수업에서 딴짓하는 친구',
  'jungle-gym-rescue': '정글짐에서 떨어질 뻔한 친구',
  'academy-homework-cover': '학원 숙제 안 해 온 친구',
  'stationery-checkout-cutting': '계산대에서 새치기당했을 때',
  'parade-seat-saving': '퍼레이드 자리 맡아 두기',
  'campfire-danger-stop': '캠프파이어에서 위험한 장난 말리기',
  'talent-show-stagefright': '장기자랑 무대 공포증',
  'soccer-injury-firstaid': '축구하다 다친 친구 돕기',
  'pet-cafe-rough-handling': '반려동물 거칠게 만지는 손님',
  'bookstore-choice-advice': '서점에서 책 고르는 친구 돕기',
  'museum-visit-loud-group': '미술관에서 시끄러운 다른 학교 학생들',
  'class-newspaper-freerider': '학급 신문에서 혼자 일 안 하는 친구',
  'snowball-fight-hurt': '눈싸움에서 세게 던져 다치게 했을 때',
  'picnic-no-lunchbox': '소풍에서 도시락 안 가져온 친구',
  'flea-market-price-haggle': '벼룩시장에서 값 깎아 달라는 친구',
  'cheer-lost-voice-help': '응원하다 목소리 안 나오는 친구',
  'school-garden-harvest-share': '텃밭 수확물 나누기 다툼',
  'art-class-copying': '옆자리 그림 따라 그리는 친구',
  'slide-climbing-wrongway': '미끄럼틀 거꾸로 오르는 친구',
  'swim-class-dive-teasing': '잠수 못한다고 놀림당하는 친구',
  'class-magazine-review': '학급 문집 글이 별로라는 평가에 속상할 때',
  'group-chat-not-invited': '단체 채팅방에 초대받지 못했을 때',
  'park-bench-litter': '공원 벤치에 남겨진 쓰레기',
  'lunch-line-hungry-reason': '배고파서 새치기한 친구 이해하기',
  'crosswalk-signal-ignoring': '빨간불에 건너려는 친구 말리기',
  'art-supplies-left-messy': '미술 재료 어지럽히고 가는 친구',
  'classroom-plant-turn-dispute': '화분 물 주기 서로 미루기',
  'campfire-junior-scared': '캠프파이어 무서워하는 동생',
  'gazebo-adults-occupying': '정자를 오래 차지한 어른들',
  'library-return-forgotten-help': '책 반납일 깜빡한 친구 돕기',
  'tablet-class-broken-device': '태블릿 고장 난 친구 돕기',
  'cafeteria-food-waste': '급식 많이 남기고 버리는 친구',
  'bike-rental-no-helmet': '헬멧 안 쓰고 자전거 타는 친구',
  'presentation-mic-broken': '발표회에서 마이크 고장 났을 때',
  'cleanup-sharp-object': '봉사활동 중 날카로운 물건 발견',
  'ice-rink-fall-support': '스케이트 타다 넘어진 친구 돕기',
  'fishcake-treat-friend': '붕어빵 친구 몫까지 계산해 주기',
  'reading-club-unprepared': '독서 모임에 책 안 읽어 온 친구',
  'school-band-instrument-mixup': '밴드부 악기 뒤바뀌었을 때',

  'class-reassignment-separation': '반 배정으로 친한 친구와 헤어졌을 때',
  'social-media-follower-envy': 'SNS 팔로워 수 비교로 위축되기',
  'puberty-mood-swings': '사춘기 감정 기복 이해하기',
  'parents-argument-anxiety': '부모님이 다투신 후 불안한 마음',
  'long-time-outsider-feeling': '전학 온 지 오래됐지만 겉도는 느낌',
  'pet-passing-grief': '반려동물이 세상을 떠났을 때',
  'pe-test-mistake-upset': '체육 실기시험에서 실수해 속상할 때',
  'report-card-parent-worry': '성적표 받고 부모님 반응이 걱정될 때',
  'friend-drifting-apart': '친한 친구가 다른 무리와 어울리며 소원해질 때',
  'game-rank-drop-upset': '온라인 게임 랭킹이 떨어져 속상할 때',
  'presentation-reaction-disappointment': '발표 후 친구들 반응이 예상과 달라 서운할 때',
  'moving-house-nostalgia': '이사로 정든 동네를 떠나야 하는 아쉬움',
  'unrequited-crush-sadness': '좋아하던 사람의 마음이 다른 곳에 있다는 걸 알았을 때',
  'team-selection-rejection': '축구 대표 선발에서 탈락했을 때',
  'sibling-leaving-home-empty': '언니(형)가 독립해 떠나며 느끼는 허전함',
  'online-class-mute-mistake-embarrassment': '온라인 수업 중 마이크를 꺼야 하는데 실수해서 창피할 때',
  'relative-appearance-comment-hurt': '친척이 외모를 지적해서 속상할 때',
  'exam-period-overwhelm': '시험 기간 부담감에 짓눌릴 때',
  'club-audition-rejection': '좋아하는 동아리 오디션에서 떨어졌을 때',
  'moving-boxes-unpacking-help': '이사 온 친구의 짐 정리를 도와주기',
  'computer-lab-file-save-help': '파일 저장 못한 친구 도와주기',
  'relay-injured-support': '계주에서 다리를 다친 친구 부축하기',
  'art-supplies-forgotten-share': '미술 준비물 안 가져온 친구와 나누기',
  'presentation-print-fail-help': '발표 자료 인쇄 안 된 친구 도와주기',
  'festival-booth-cleanup-help': '축제 부스 정리를 늦게까지 도와주기',
  'broken-glasses-explain-help': '안경을 깨뜨린 친구 대신 사정을 설명해 주기',
  'bike-chain-fix-help': '자전거 체인이 빠진 친구 도와주기',
  'jumprope-test-encourage-help': '줄넘기 시험에서 실수한 친구 격려하기',
  'classroom-library-boxes-help': '무거운 학급 문고 상자 옮기는 것 도와주기',
  'overslept-supplies-lend-help': '늦잠 자서 준비물 못 챙긴 친구에게 빌려주기',
  'unfamiliar-food-encourage-help': '낯선 급식 메뉴를 꺼리는 친구 다독이기',
  'fieldtrip-lost-friend-help': '체험학습 중 길을 잃은 친구 찾아주기',
  'online-class-login-help': '온라인 수업 접속 방법 몰라 헤매는 친구 도와주기',
  'trip-luggage-overweight-help': '수학여행 짐 무게 초과로 곤란한 친구 도와주기',
  'injured-hand-tray-help': '손 다친 친구 대신 식판 들어주기',
  'misaligned-answer-sheet-help': '답안지 밀려 쓴 친구 도와 확인하기',
  'injured-arm-shoelace-help': '팔 다친 친구의 신발끈 묶어주기',
  'bulletin-board-decorate-help': '학급 게시판 꾸미기 혼자 남은 친구 돕기',
  'gym-clothes-forgot-lend-help': '체육복을 깜빡한 친구에게 빌려주기',
  'software-usage-teach-help': '낯선 프로그램 사용법 몰라 헤매는 친구 알려주기',
  'stage-props-locate-help': '무대 뒤에서 소품 위치 몰라 헤매는 친구 도와주기',
  'allergy-label-read-help': '급식 알레르기 표시 못 읽는 저학년 도와주기',
  'gym-mats-cleanup-help': '체육관 매트 정리를 혼자 하는 친구 돕기',
  'announcement-missed-transferstudent-help': '안내방송을 못 들어 헤매는 전학생 도와주기',
  'artwork-carry-stumble-help': '미술 작품 운반 중 넘어질 뻔한 친구 잡아주기',
  'supply-money-forgot-lend-help': '준비물 값을 깜빡한 친구에게 빌려주기',
  'lunch-line-dizzy-support-help': '급식 줄에서 어지러움을 느끼는 친구 부축하기',
  'deep-cleaning-desks-move-help': '대청소 날 무거운 책상 옮기기 함께 돕기',
  'costume-zipper-stuck-help': '학예회 무대의상 지퍼가 안 열리는 친구 도와주기',
  'library-late-fee-worry-help': '반납 기한 넘긴 친구 벌금 걱정 덜어주기',
  'ankle-injury-ice-help': '체육시간 다친 발목에 얼음찜질 도와주기',
  'online-purchase-mistake-refund': '온라인 구매 실수로 잘못 받은 환불',
  'group-project-credit-honesty': '모둠 과제 발표에서 역할 정직하게 밝히기',
  'homework-copy-temptation-honesty': '숙제를 베끼고 싶은 유혹 이겨내기',
  'littering-hide-evidence-honesty': '실수로 어지른 것을 몰래 숨기고 싶은 마음',
  'boardgame-cheating-temptation-honesty': '보드게임에서 몰래 반칙하고 싶은 마음',
  'window-break-admit-honesty': '실수로 창문을 깬 것을 인정하기',
  'answer-key-unauthorized-use-honesty': '몰래 정답지를 보고 싶은 유혹 이겨내기',
  'extra-snack-portion-unfair-honesty': '몰래 간식을 더 많이 챙기고 싶은 마음',
  'quiz-score-change-honesty': '몰래 시험 점수를 고치고 싶은 유혹',
  'blame-not-admitting-fight-honesty': '싸움을 먼저 시작한 것을 인정하지 않으려는 마음',
  'bike-borrow-without-asking-honesty': '허락 없이 친구 자전거를 타고 싶은 마음',
  'vending-machine-overpaid-change-honesty': '자판기에서 거스름돈을 더 받았을 때',
  'playground-equipment-break-admit-honesty': '놀이기구를 망가뜨린 것을 인정하기',
  'group-chat-screenshot-share-honesty': '단체 채팅 내용을 몰래 캡처해 퍼뜨리고 싶은 유혹',
  'idcard-borrow-unauthorized-honesty': '다른 사람의 회원증을 몰래 쓰고 싶은 마음',
  'exam-cheat-sheet-hide-honesty': '시험 중 몰래 커닝 쪽지를 숨기고 싶은 유혹',
  'online-idea-credit-steal-honesty': '온라인에 남의 아이디어를 내 것처럼 올리고 싶은 유혹',
  'library-book-borrow-someone-elses-name-honesty': '다른 사람 이름으로 몰래 책을 빌리고 싶은 마음',
  'shared-fund-spend-without-telling-honesty': '모둠 공금을 몰래 쓰고 싶은 유혹',
  'shared-snack-secretly-eat-honesty': '함께 나눌 간식을 몰래 먼저 먹고 싶은 마음',
  'found-earbuds-not-return-honesty': '주운 이어폰을 돌려주지 않고 싶은 마음',
  'fire-alarm-blame-lie-honesty': '화재경보기를 건드린 것을 숨기고 싶은 마음',
  'no-food-zone-sneak-eating-honesty': '음식 반입 금지 구역에서 몰래 먹고 싶은 마음',
  'shared-file-delete-not-admit-honesty': '모둠 파일을 실수로 지운 것을 인정하기',
  'cake-slice-unfair-bigger-honesty': '케이크를 몰래 더 큰 조각으로 가져가고 싶은 마음',
  'parent-signature-forge-honesty': '부모님 서명을 몰래 따라 쓰고 싶은 마음',
  'game-cheat-code-claim-skill-honesty': '게임에서 편법을 쓰고 실력이라고 속이고 싶은 마음',
  'class-money-collection-honesty': '학급비 걷은 돈을 정직하게 관리하기',
  'used-item-sell-defect-honesty': '중고 물건을 팔 때 흠집을 숨기고 싶은 마음',
  'test-answer-peek-neighbor-honesty': '옆자리 답을 몰래 보고 싶은 유혹',
  'class-survey-fake-answer-honesty': '학급 설문에 거짓으로 답하고 싶은 마음',
  'borrowed-tool-damage-hide-honesty': '빌린 도구를 망가뜨린 것을 숨기고 싶은 마음',
  'lab-safety-goggles-skip': '실험실에서 보호 안경 없이 실험하기',
  'stairs-jumping-two-steps': '계단에서 두 칸씩 뛰어내려가기',
  'bike-lane-wrong-way': '자전거 도로에서 역주행하기',
  'inline-skate-no-gear': '보호장구 없이 인라인스케이트 타기',
  'emergency-exit-blocked': '비상구를 물건으로 막아 두기',
  'chemicals-mix-danger': '화학 약품을 함부로 섞으려 하기',
  'goalpost-hanging-danger': '축구 골대에 매달려 흔들기',
  'hot-soup-running-danger': '뜨거운 국을 들고 뛰기',
  'pool-diving-forbidden-zone': '다이빙 금지 구역에서 뛰어들기',
  'indoor-shoes-skip-rule': '실내화로 갈아신지 않고 교실 들어오기',
  'jaywalking-after-school': '하교 시간에 무단횡단하려 하기',
  'cutter-knife-playing-danger': '커터칼을 장난감처럼 휘두르기',
  'elevator-overcapacity': '엘리베이터 정원 초과로 타려 하기',
  'electrical-outlet-overload': '전기 콘센트에 여러 개 꽂아 과부하 만들기',
  'schoolbus-no-seatbelt-standing': '스쿨버스에서 안전벨트 없이 일어서 있기',
  'gym-window-hanging-danger': '체육관 창문에 매달려 장난치기',
  'kitchen-restricted-entry': '급식 조리실에 허락 없이 들어가려 하기',
  'outlet-touching-junior-danger': '콘센트를 만지려는 저학년 말리기',
  'cliff-edge-photo-danger': '낭떠러지 근처에서 사진 찍으려 하기',
  'self-study-sneak-out': '자율학습 시간에 몰래 빠져나가려 하기',
  'umbrella-swinging-danger': '우산을 창처럼 휘두르기',
  'fire-drill-horseplay': '화재 대피 훈련 중 장난치며 뛰어다니기',
  'kickboard-no-helmet-fast': '안전모 없이 킥보드를 빠르게 타기',
  'scissors-throwing-play': '가위를 던지며 장난치기',
  'track-wrong-direction-running': '운동장 트랙을 반대 방향으로 뛰기',
  'earphones-loud-crossing-danger': '이어폰을 크게 틀고 횡단보도 건너기',
  'campfire-unattended-leave': '캠프파이어 불씨를 정리 안 하고 자리 뜨기',
  'wet-floor-no-sign': '미끄러운 바닥에 표시 없이 두기',
  'rooftop-unauthorized-access': '학교 옥상에 몰래 올라가려 하기',
  'swing-standing-overswing-danger': '그네를 서서 과하게 흔들기',
  'kitchen-knife-junior-touch': '급식실 칼을 만지려는 저학년 말리기',
  'window-leaning-out-danger': '자습 시간에 창문 밖으로 몸 내밀기',
  'fire-extinguisher-play-danger': '소화기를 장난감처럼 만지려 하기',
  'nickname-teasing-target': '별명으로 놀림받는 친구',
  'sns-tag-exclusion': 'SNS에서 특정 친구만 태그 안 하기',
  'team-pick-always-last': '편 가르기에서 항상 마지막으로 뽑히는 친구',
  'lunch-seat-subtle-exclusion': '급식 자리에 못 앉게 은근히 막기',
  'dialect-teasing-transferstudent': '사투리를 쓴다고 놀림받는 전학생',
  'stutter-mimicking-teasing': '발표 중 목소리 떨림을 따라 하며 놀리기',
  'group-opinion-ignored-bullying': '모둠에서 의견을 무시당하는 친구',
  'game-kick-low-skill-bullying': '실력 낮다고 게임에서 강퇴당하는 친구',
  'glasses-teasing': '안경 썼다고 놀림받는 친구',
  'weight-teasing': '몸무게로 놀림받는 친구',
  'old-supplies-mocked': '준비물이 낡았다고 무시당하기',
  'brand-shoes-exclusion': '유명 브랜드 신발이 없다고 무시당하기',
  'store-line-subtle-exclusion': '매점에서 은근히 자리 안 비켜주며 소외시키기',
  'drawing-skill-mocked': '그림 실력이 부족하다고 비웃음 당하기',
  'afterschool-seat-taken-exclusion': '방과후 수업에서 자리 뺏기',
  'slang-unfamiliar-teasing': '줄임말을 몰라서 놀림받는 전학생',
  'body-odor-gossip-bullying': '몸에서 냄새난다고 뒤에서 흉보기',
  'no-pet-teasing': '반려동물이 없다고 놀림받는 친구',
  'kickball-mistake-blamed-repeatedly': '발야구 실수로 계속 탓받는 친구',
  'hiding-belongings-prank-bullying': '친구 물건을 몰래 숨기는 장난',
  'groupchat-ignore-one-person': '단체 채팅에서 한 명만 답장 안 해 주기',
  'walking-style-mimicking-teasing': '걸음걸이를 따라 하며 놀리기',
  'test-score-public-comparison-teasing': '시험 점수를 공개 비교하며 놀리기',
  'artwork-secretly-damaged-bullying': '미술 작품을 몰래 훼손하며 골탕 먹이기',
  'name-distortion-teasing': '이름을 이상하게 바꿔 부르며 놀리기',
  'anonymous-board-badmouthing': '온라인 익명 게시판에 험담 올리기',
  'presentation-secret-jeering': '발표 후 몰래 야유하기',
  'leftover-food-public-shaming': '급식 남긴다고 대놓고 지적하며 창피 주기',
  'small-body-seat-denied': '몸이 작다고 자리 양보 안 하며 무시하기',
  'dating-rumor-teasing': '사귄다는 소문으로 놀리며 괴롭히기',
  'group-assignment-repeatedly-excluded': '조 편성에서 계속 빠뜨리기',
  'slow-reply-badmouthing': '문자 답장이 느리다고 뒤에서 흉보기',
  'changing-room-body-comment-bullying': '체육복 갈아입을 때 몸매 지적하기',
  'class-wide-mimicking-mockery': '특정 친구 흉내를 내며 반 전체가 웃기',
  'meme-photo-edit-teasing': '인터넷 밈으로 친구 사진 합성해 놀리기',
  'accent-mimicking-teasing': '전학생 억양을 따라 하며 놀리기',
  'effort-belittling-teasing': '친구가 노력한 결과물을 깎아내리기',
  'group-photo-deliberate-crop-exclusion': '단체 사진에서 한 명만 의도적으로 자르기',
  'wheelchair-ramp-yield': '휠체어 이용자를 위해 경사로 양보하기',
  'pregnant-seat-yield': '임산부에게 자리 양보하기',
  'noise-sensitive-friend-consideration': '소음에 예민한 친구를 배려하기',
  'left-handed-desk-share': '왼손잡이 친구를 위해 자리 배려하기',
  'elderly-heavy-bag-help-consideration': '무거운 짐을 든 어르신 배려하기',
  'visually-impaired-guide-consideration': '시각장애인의 길 안내 배려하기',
  'multicultural-family-language-consideration': '다문화 가정 친구의 언어를 배려하기',
  'hearing-impaired-classmate-consideration': '청각이 불편한 친구를 배려하기',
  'food-allergy-menu-consideration': '알레르기가 있는 친구를 위해 메뉴 배려하기',
  'wheelchair-classroom-space-consideration': '휠체어 친구를 위해 교실 공간 배려하기',
  'stuttering-friend-listen-consideration': '말이 느린 친구의 이야기를 끝까지 들어주기',
  'religious-diet-menu-consideration': '종교적 이유로 못 먹는 음식 배려하기',
  'younger-sibling-pace-consideration': '걸음이 느린 동생 속도 맞춰 주기',
  'new-country-food-culture-consideration': '다른 나라 문화의 친구 식습관 배려하기',
  'test-anxiety-quiet-consideration': '시험 전 예민한 친구를 조용히 배려하기',
  'grieving-friend-space-consideration': '슬픔에 빠진 친구에게 시간을 주기',
  'anxious-newcomer-pace-consideration': '낯가리는 새 친구에게 천천히 다가가기',
  'motion-sick-carsick-consideration': '차멀미하는 친구를 위해 자리 배려하기',
  'colorblind-friend-chart-consideration': '색맹인 친구를 위해 자료 배려하기',
  'single-parent-family-topic-consideration': '가족 이야기에서 한부모 가정 친구 배려하기',
  'wheelchair-fieldtrip-route-consideration': '체험학습 동선을 휠체어 친구에 맞춰 배려하기',
  'diabetic-friend-snack-consideration': '당뇨가 있는 친구를 위해 간식 배려하기',
  'anxiety-disorder-friend-consideration': '불안이 심한 친구를 배려하기',
  'prosthetic-limb-friend-consideration': '의족을 쓰는 친구를 배려하기',
  'jetlag-exchange-student-consideration': '시차 적응 못한 교환학생 배려하기',
  'stroller-doorway-yield-consideration': '유모차 지나가도록 문 잡아 드리기',
  'sensory-overload-classroom-consideration': '감각이 예민한 친구를 위해 교실 환경 배려하기',
  'crutches-classmate-carry-consideration': '목발 짚은 친구의 짐 들어주기',
  'divorced-parents-topic-consideration': '부모님이 이혼한 친구 화제 배려하기',
  'braces-eating-difficulty-consideration': '치아교정 중인 친구 급식 배려하기',
  'reading-disability-friend-consideration': '읽기가 느린 친구 배려하기',
  'medication-time-schedule-consideration': '정해진 시간에 약을 먹어야 하는 친구 배려하기',
  'wheelchair-sports-rule-adjustment-consideration': '체육 활동 규칙을 휠체어 친구에 맞춰 조정하기',
  'grandparents-tech-teach-consideration': '스마트폰 사용이 서투신 조부모님 배려하기',
  'burn-scar-classmate-consideration': '화상 흉터가 있는 친구 배려하기',
  'lactose-intolerant-milk-consideration': '우유를 못 마시는 친구 배려하기',
  'wheelchair-museum-exhibit-height-consideration': '전시물 높이를 휠체어 친구에 맞춰 배려하기',
  'group-topic-vote-disagreement': '모둠 주제 투표 결과에 불만 갖기',
  'shared-locker-space-dispute': '사물함 공간을 두고 다투기',
  'playlist-choice-conflict': '학급 파티 음악 선곡을 두고 다투기',
  'debate-club-opinion-clash': '토론 동아리에서 의견이 부딪히기',
  'shared-room-cleanup-schedule-conflict': '기숙사 방 청소 당번을 두고 다투기',
  'gift-exchange-value-conflict': '선물 교환에서 가격 차이로 다투기',
  'seat-swap-request-conflict': '자리 바꿔달라는 요청을 두고 다투기',
  'club-leader-election-conflict': '동아리 회장 선거로 사이가 나빠지기',
  'shared-notebook-writing-disagreement': '공동 일기장 내용을 두고 의견 충돌하기',
  'sports-position-preference-conflict': '축구 포지션을 두고 다투기',
  'shared-plant-care-method-conflict': '학급 화분 관리 방법으로 다투기',
  'birthday-party-guest-list-conflict': '생일 파티 초대 명단으로 다투기',
  'shared-toy-turn-order-conflict': '보드게임 순서를 두고 다투기',
  'shared-earphone-volume-conflict': '이어폰 소리 크기로 다투기',
  'class-mascot-name-vote-conflict': '학급 마스코트 이름을 두고 다투기',
  'homework-help-repayment-conflict': '숙제 도와준 것에 대한 보답 문제로 다투기',
  'field-trip-buddy-pairing-conflict': '체험학습 짝꿍 정하기로 다투기',
  'video-call-schedule-conflict': '온라인 모둠 회의 시간을 두고 다투기',
  'costume-color-choice-conflict': '학예회 의상 색깔을 두고 다투기',
  'shared-computer-time-conflict': '컴퓨터실에서 사용 순서로 다투기',
  'shared-blanket-camp-conflict': '캠핑에서 이불을 두고 다투기',
  'presentation-order-conflict': '발표 순서를 두고 다투기',
  'shared-charger-priority-conflict': '충전기 사용 순서를 두고 다투기',
  'team-project-deadline-blame-conflict': '모둠 과제 마감 늦은 것으로 서로 탓하기',
  'shared-recipe-cooking-class-conflict': '요리 실습에서 레시피 방법으로 다투기',
  'nickname-usage-disagreement-conflict': '별명을 부르는 문제로 의견이 갈리기',
  'shared-tent-space-conflict': '캠핑 텐트 공간 배치로 다투기',
  'class-vote-tie-conflict': '학급 투표 동점으로 갈등 생기기',
  'shared-basketball-court-time-conflict': '농구장 사용 시간을 두고 다투기',
  'group-report-format-conflict': '보고서 형식을 두고 의견 대립하기',
  'shared-badminton-racket-conflict': '배드민턴 라켓을 두고 다투기',
  'movie-genre-choice-conflict': '함께 볼 영화 장르로 다투기',
  'shared-picnic-spot-conflict': '소풍 자리를 먼저 차지하려다 다투기',
  'shared-drawing-tablet-turn-conflict': '태블릿 그림 그리기 순서로 다투기',
  'shared-microphone-karaoke-conflict': '노래방에서 마이크 순서로 다투기',
  'shared-recess-ball-conflict': '쉬는 시간 공놀이 순서로 다투기',
  'shared-fan-summer-conflict': '더운 여름날 선풍기 자리로 다투기',
  'movie-theater-phone-light': '영화관에서 휴대폰 밝게 켜기',
  'elevator-loud-phonecall': '엘리베이터에서 큰 소리로 통화하기',
  'restaurant-running-around': '식당에서 뛰어다니기',
  'public-transport-eating-smelly-food': '대중교통에서 냄새 나는 음식 먹기',
  'library-shoes-on-table': '도서관 책상에 신발 신은 발 올리기',
  'swimming-pool-running-poolside': '수영장 물가에서 뛰어다니기',
  'concert-hall-standing-up-blocking': '공연장에서 갑자기 일어나 시야 가리기',
  'restroom-line-cutting-manners': '화장실 줄에서 새치기하기',
  'museum-flash-photography': '박물관에서 플래시로 사진 찍기',
  'park-bike-pedestrian-path': '공원 산책로에서 빠르게 자전거 타기',
  'church-temple-loud-talking': '예배당·법당에서 큰 소리로 떠들기',
  'hospital-waiting-room-noise': '병원 대기실에서 뛰어다니며 소란 피우기',
  'stadium-trash-leaving': '경기장 관람석에 쓰레기 두고 가기',
  'cafe-table-hogging-manners': '카페에서 자리만 맡아두고 오래 비우기',
  'apartment-late-night-noise': '아파트에서 늦은 밤 뛰며 층간소음 내기',
  'grocery-store-touching-food': '마트에서 식품을 함부로 만지기',
  'airplane-seat-reclining-manners': '비행기에서 갑자기 좌석 뒤로 젖히기',
  'public-restroom-water-splash': '공중화장실에서 물 튀기며 장난치기',
  'shop-mannequin-messing': '옷가게에서 진열 옷 어지럽히기',
  'ferry-deck-leaning-over': '유람선 갑판 난간에 몸을 기울이기',
  'waiting-room-shoes-on-chair': '대기실 의자에 신발 신고 눕기',
  'zoo-tapping-glass-teasing-animal': '동물원에서 유리를 두드리며 동물 괴롭히기',
  'restaurant-loud-video-no-headphones': '식당에서 헤드폰 없이 영상 크게 틀기',
  'library-loud-group-chatting': '도서관에서 친구들과 큰 소리로 대화하기',
  'airport-security-line-cutting': '공항 보안 검색대 줄에서 새치기하기',
  'wedding-hall-running-around': '결혼식장에서 뛰어다니며 소란 피우기',
  'shared-office-desk-messy': '공용 작업 공간을 어지럽히고 안 치우기',
  'taxi-door-slamming': '택시에서 문을 세게 닫기',
  'public-park-flower-picking': '공원 화단의 꽃을 함부로 꺾기',
  'sauna-loud-splashing': '찜질방·목욕탕에서 물장구치며 소란 피우기',
  'train-station-blocking-doorway': '지하철 출입문 앞을 막고 서 있기',
  'classroom-hallway-running-manners': '학교 복도에서 빠르게 뛰어다니기',
  'bank-atm-line-crowding': 'ATM 앞에서 순서 없이 몰려들기',
  'shared-garden-plot-trampling': '공동 텃밭을 함부로 밟고 다니기',
  'photo-studio-touching-props': '사진관에서 소품을 함부로 만지기',
  'shared-charging-station-hogging': '공용 충전소에서 자리 독차지하기',
  'shared-vending-machine-shaking': '자판기를 흔들거나 발로 차기',
  'campground-shared-facility-mess': '캠핑장 공용 시설을 어지럽히고 안 치우기',
  'shared-umbrella-stand-messing': '건물 우산꽂이에서 남의 우산 함부로 쓰기',
  'shared-printer-hogging-manners': '공용 프린터 앞에서 순서 없이 계속 인쇄하기',
  'science-fair-team-experiment': '과학의 날 모둠 실험 함께 준비하기',
  'class-mural-painting-together': '학급 벽화를 함께 그리기',
  'relay-race-team-strategy': '이어달리기 작전을 함께 세우기',
  'school-festival-booth-teamwork': '학교 축제 부스를 함께 준비하기',
  'orchestra-practice-together': '합주 연습에서 서로 맞춰 가기',
  'cooking-class-team-roles': '요리 실습에서 역할 나눠 협동하기',
  'garden-harvest-teamwork': '학교 텃밭 수확을 함께 나누기',
  'sports-day-tug-of-war-teamwork': '체육대회 줄다리기에서 힘을 모으기',
  'newspaper-club-role-division': '학급 신문 만들기 역할 나누기',
  'talent-show-group-act-practice': '장기자랑 단체 공연을 함께 연습하기',
  'debate-team-role-assignment': '토론 대회에서 역할 나눠 준비하기',
  'robot-competition-team-build': '로봇 대회에서 팀으로 조립하기',
  'choir-harmony-practice-teamwork': '합창에서 화음을 맞추며 협동하기',
  'model-building-collaborative-project': '모형 만들기 프로젝트를 함께 완성하기',
  'field-day-relay-baton-pass-teamwork': '체육대회 배턴 넘기기를 연습하며 협동하기',
  'book-club-discussion-teamwork': '독서 모임에서 생각을 나누며 협동하기',
  'aquarium-fish-tank-cleaning-teamwork': '학급 어항 청소를 함께 나누기',
  'class-flag-design-teamwork': '학급 깃발 디자인을 함께 정하기',
  'science-museum-quiz-team-mission': '과학관 미션 활동을 팀으로 해결하기',
  'class-newsletter-editing-teamwork': '학급 소식지 편집을 함께 검토하기',
  'camping-trip-meal-prep-teamwork': '캠핑에서 식사 준비를 함께 나누기',
  'class-recycling-sorting-teamwork': '학급 분리수거를 함께 나누기',
  'science-club-observation-log-teamwork': '과학 동아리 관찰 일지를 함께 기록하기',
  'community-service-team-cleanup': '봉사활동에서 팀을 이뤄 청소하기',
  'class-vegetable-garden-planning-teamwork': '텃밭 작물 배치를 함께 계획하기',
  'school-broadcast-team-roles': '학교 방송반에서 역할 나눠 협동하기',
  'school-farm-animal-care-teamwork': '학급 동물 돌봄 일정을 함께 짜기',
  'group-science-report-writing-teamwork': '모둠 과학 보고서를 함께 작성하기',
  'field-trip-group-schedule-planning': '체험학습 모둠 일정을 함께 계획하기',
  'class-time-capsule-teamwork': '학급 타임캡슐을 함께 준비하기',
  'class-olympic-cheer-squad-teamwork': '학급 응원단을 함께 꾸리기',
  'library-book-fair-setup-teamwork': '도서관 북페어 부스를 함께 꾸미기',
  'school-play-set-design-teamwork': '학예회 무대 배경을 함께 제작하기',
  'class-flower-bed-teamwork': '학교 화단 가꾸기를 함께 나누기',
  'class-quiz-bowl-team-strategy': '퀴즈 대회 팀 전략을 함께 세우기',
  'class-mock-trial-role-teamwork': '모의재판 역할극을 함께 준비하기',
  'class-recipe-book-teamwork': '학급 레시피북을 함께 만들기',
  'class-mural-cleanup-crew-teamwork': '벽화 그린 뒤 함께 뒷정리하기',
  'class-podcast-production-teamwork': '학급 팟캐스트를 함께 제작하기',
  'class-science-experiment-cleanup-teamwork': '실험 후 실험 도구를 함께 정리하기',
  'class-board-game-design-teamwork': '학급 보드게임을 함께 만들기',
  'class-yearbook-photo-collection-teamwork': '학급 졸업앨범 사진을 함께 모으기',
  'class-relay-quiz-team-support': '이어달리기 퀴즈에서 서로 힌트 주고받기',
}

export function titleOf(item: SituationItem): string {
  return TITLES[item.id] ?? item.questions[0].question
}

export type SituationGroupKey =
  | 'help'
  | 'emotion'
  | 'conflict'
  | 'bullying'
  | 'consideration'
  | 'rules'
  | 'honesty'
  | 'manners'
  | 'teamwork'
  | 'etc'

export const GROUP_DEFS: { key: SituationGroupKey; label: string; emoji: string }[] = [
  { key: 'help', label: '친구 돕기', emoji: '🤝' },
  { key: 'emotion', label: '감정 이해·위로', emoji: '💗' },
  { key: 'conflict', label: '갈등 해결', emoji: '🤔' },
  { key: 'bullying', label: '따돌림·놀림 대처', emoji: '🛡️' },
  { key: 'consideration', label: '배려·양보', emoji: '🌷' },
  { key: 'rules', label: '규칙·안전 지키기', emoji: '🚦' },
  { key: 'honesty', label: '정직·책임감', emoji: '✋' },
  { key: 'manners', label: '공공장소 예절', emoji: '🏛️' },
  { key: 'teamwork', label: '협동·모둠 활동', emoji: '👥' },
  { key: 'etc', label: '기타', emoji: '📌' },
]

// Situation ids don't carry any grouping info of their own, so each one is
// hand-assigned to a theme here. Anything created later via the admin screen
// (random uuid ids) falls back to the 'etc' bucket below.
const GROUP_OF: Record<string, SituationGroupKey> = {
  'fell-down': 'help',
  birthday: 'emotion',
  'no-umbrella': 'emotion',
  'toy-fight': 'conflict',
  'perfect-score': 'emotion',
  'group-project': 'teamwork',
  gossip: 'bullying',
  'team-sports': 'emotion',
  'borrow-item': 'honesty',
  bystander: 'bullying',
  'broken-item': 'honesty',
  'new-student': 'consideration',
  'lost-item': 'emotion',
  'unfair-blame': 'emotion',
  'line-cutting': 'rules',
  'not-picked': 'emotion',
  'sibling-turn': 'rules',
  'compliment-jealousy': 'emotion',
  'promise-broken': 'conflict',
  'accidental-hurt': 'honesty',
  'cheating-on-test': 'honesty',
  'chat-exclusion': 'bullying',
  'losing-competition': 'emotion',
  'plagiarism-temptation': 'honesty',
  'rumor-spreading': 'bullying',
  'class-pet-neglect': 'honesty',
  'found-money': 'honesty',
  'exam-stress-friend': 'emotion',
  'sibling-comparison': 'emotion',
  'team-blame-game': 'conflict',
  'secret-diary-peek': 'honesty',
  'language-barrier-student': 'consideration',
  'borrowed-item-broken': 'honesty',
  'appearance-teasing-witness': 'bullying',
  'presentation-freeze': 'emotion',
  'credit-hogging': 'teamwork',
  'online-mean-comment': 'bullying',
  'unfair-scolding': 'emotion',
  'wheelchair-friend-inclusion': 'consideration',
  'littering-witness': 'manners',
  'spilled-paint-artclass': 'help',
  'library-shelf-help': 'help',
  'swing-cutting-line': 'rules',
  'picky-eater-teasing': 'bullying',
  'pool-water-fear': 'emotion',
  'heavy-backpack-help': 'help',
  'science-experiment-mistake': 'help',
  'off-key-singing-tease': 'bullying',
  'dodgeball-selfblame': 'emotion',
  'academy-bus-seat': 'consideration',
  'stationery-store-mischarge': 'honesty',
  'amusement-park-scared-sibling': 'emotion',
  'camping-tent-teamwork': 'teamwork',
  'reading-room-noise': 'manners',
  'classroom-cleanup-alone': 'help',
  'bus-stop-rain-grandma': 'consideration',
  'museum-touching-artwork': 'manners',
  'soccer-foul-forgive': 'conflict',
  'sandcastle-destroyed': 'honesty',
  'classroom-meeting-ignored': 'emotion',
  'online-game-blame': 'conflict',
  'choir-practice-teasing': 'bullying',
  'volunteer-giving-up': 'emotion',
  'new-student-welcome-party': 'consideration',
  'field-trip-room-assignment': 'conflict',
  'vet-waiting-room-comfort': 'emotion',
  'salon-cutting-line': 'rules',
  'seesaw-weight-exclusion': 'bullying',
  'school-garden-watering': 'honesty',
  'lunch-line-junior-cutting': 'rules',
  'school-play-forgotten-line': 'help',
  'afterschool-alone-classroom': 'consideration',
  'stairs-junior-fall': 'help',
  'stationery-share-refused': 'emotion',
  'tag-game-rule-breaking': 'rules',
  'allergy-food-consideration': 'consideration',
  'fieldtrip-busmotionsick': 'help',
  'dogwalk-turn-conflict': 'conflict',
  'festival-booth-empty': 'emotion',
  'invention-idea-suspicion': 'conflict',
  'online-class-mic-mistake': 'honesty',
  'playground-bike-not-yielding': 'consideration',
  'class-library-book-damage': 'honesty',
  'taekwondo-belt-test-fail': 'emotion',
  'playground-shade-exhausted': 'help',
  'schoolstore-no-money': 'consideration',
  'quiz-contest-wrong-answer': 'emotion',
  'art-exhibit-low-score': 'emotion',
  'relay-race-baton-drop': 'emotion',
  'winter-camp-homesick': 'emotion',
  'jungle-gym-turn-pushed': 'rules',
  'lunchroom-tray-mess': 'manners',
  'math-class-crying': 'emotion',
  'art-show-missing-work': 'conflict',
  'stationery-shop-theft-witness': 'honesty',
  'playground-dog-fear': 'emotion',
  'new-cook-greeting': 'manners',
  'library-adult-phonecall': 'manners',
  'tug-of-war-weak-teasing': 'conflict',
  'art-class-sharing-paper': 'consideration',
  'online-class-camera-off': 'rules',
  'jungle-gym-rescue': 'help',
  'academy-homework-cover': 'honesty',
  'stationery-checkout-cutting': 'rules',
  'parade-seat-saving': 'rules',
  'campfire-danger-stop': 'rules',
  'talent-show-stagefright': 'emotion',
  'soccer-injury-firstaid': 'help',
  'pet-cafe-rough-handling': 'manners',
  'bookstore-choice-advice': 'help',
  'museum-visit-loud-group': 'manners',
  'class-newspaper-freerider': 'teamwork',
  'snowball-fight-hurt': 'honesty',
  'picnic-no-lunchbox': 'consideration',
  'flea-market-price-haggle': 'conflict',
  'cheer-lost-voice-help': 'help',
  'school-garden-harvest-share': 'conflict',
  'art-class-copying': 'honesty',
  'slide-climbing-wrongway': 'rules',
  'swim-class-dive-teasing': 'bullying',
  'class-magazine-review': 'emotion',
  'group-chat-not-invited': 'bullying',
  'park-bench-litter': 'manners',
  'lunch-line-hungry-reason': 'rules',
  'crosswalk-signal-ignoring': 'rules',
  'art-supplies-left-messy': 'teamwork',
  'classroom-plant-turn-dispute': 'teamwork',
  'campfire-junior-scared': 'emotion',
  'gazebo-adults-occupying': 'rules',
  'library-return-forgotten-help': 'help',
  'tablet-class-broken-device': 'help',
  'cafeteria-food-waste': 'manners',
  'bike-rental-no-helmet': 'rules',
  'presentation-mic-broken': 'help',
  'cleanup-sharp-object': 'rules',
  'ice-rink-fall-support': 'help',
  'fishcake-treat-friend': 'consideration',
  'reading-club-unprepared': 'teamwork',
  'school-band-instrument-mixup': 'conflict',

  'class-reassignment-separation': 'emotion',
  'social-media-follower-envy': 'emotion',
  'puberty-mood-swings': 'emotion',
  'parents-argument-anxiety': 'emotion',
  'long-time-outsider-feeling': 'emotion',
  'pet-passing-grief': 'emotion',
  'pe-test-mistake-upset': 'emotion',
  'report-card-parent-worry': 'emotion',
  'friend-drifting-apart': 'emotion',
  'game-rank-drop-upset': 'emotion',
  'presentation-reaction-disappointment': 'emotion',
  'moving-house-nostalgia': 'emotion',
  'unrequited-crush-sadness': 'emotion',
  'team-selection-rejection': 'emotion',
  'sibling-leaving-home-empty': 'emotion',
  'online-class-mute-mistake-embarrassment': 'emotion',
  'relative-appearance-comment-hurt': 'emotion',
  'exam-period-overwhelm': 'emotion',
  'club-audition-rejection': 'emotion',
  'moving-boxes-unpacking-help': 'help',
  'computer-lab-file-save-help': 'help',
  'relay-injured-support': 'help',
  'art-supplies-forgotten-share': 'help',
  'presentation-print-fail-help': 'help',
  'festival-booth-cleanup-help': 'help',
  'broken-glasses-explain-help': 'help',
  'bike-chain-fix-help': 'help',
  'jumprope-test-encourage-help': 'help',
  'classroom-library-boxes-help': 'help',
  'overslept-supplies-lend-help': 'help',
  'unfamiliar-food-encourage-help': 'help',
  'fieldtrip-lost-friend-help': 'help',
  'online-class-login-help': 'help',
  'trip-luggage-overweight-help': 'help',
  'injured-hand-tray-help': 'help',
  'misaligned-answer-sheet-help': 'help',
  'injured-arm-shoelace-help': 'help',
  'bulletin-board-decorate-help': 'help',
  'gym-clothes-forgot-lend-help': 'help',
  'software-usage-teach-help': 'help',
  'stage-props-locate-help': 'help',
  'allergy-label-read-help': 'help',
  'gym-mats-cleanup-help': 'help',
  'announcement-missed-transferstudent-help': 'help',
  'artwork-carry-stumble-help': 'help',
  'supply-money-forgot-lend-help': 'help',
  'lunch-line-dizzy-support-help': 'help',
  'deep-cleaning-desks-move-help': 'help',
  'costume-zipper-stuck-help': 'help',
  'library-late-fee-worry-help': 'help',
  'ankle-injury-ice-help': 'help',
  'online-purchase-mistake-refund': 'honesty',
  'group-project-credit-honesty': 'honesty',
  'homework-copy-temptation-honesty': 'honesty',
  'littering-hide-evidence-honesty': 'honesty',
  'boardgame-cheating-temptation-honesty': 'honesty',
  'window-break-admit-honesty': 'honesty',
  'answer-key-unauthorized-use-honesty': 'honesty',
  'extra-snack-portion-unfair-honesty': 'honesty',
  'quiz-score-change-honesty': 'honesty',
  'blame-not-admitting-fight-honesty': 'honesty',
  'bike-borrow-without-asking-honesty': 'honesty',
  'vending-machine-overpaid-change-honesty': 'honesty',
  'playground-equipment-break-admit-honesty': 'honesty',
  'group-chat-screenshot-share-honesty': 'honesty',
  'idcard-borrow-unauthorized-honesty': 'honesty',
  'exam-cheat-sheet-hide-honesty': 'honesty',
  'online-idea-credit-steal-honesty': 'honesty',
  'library-book-borrow-someone-elses-name-honesty': 'honesty',
  'shared-fund-spend-without-telling-honesty': 'honesty',
  'shared-snack-secretly-eat-honesty': 'honesty',
  'found-earbuds-not-return-honesty': 'honesty',
  'fire-alarm-blame-lie-honesty': 'honesty',
  'no-food-zone-sneak-eating-honesty': 'honesty',
  'shared-file-delete-not-admit-honesty': 'honesty',
  'cake-slice-unfair-bigger-honesty': 'honesty',
  'parent-signature-forge-honesty': 'honesty',
  'game-cheat-code-claim-skill-honesty': 'honesty',
  'class-money-collection-honesty': 'honesty',
  'used-item-sell-defect-honesty': 'honesty',
  'test-answer-peek-neighbor-honesty': 'honesty',
  'class-survey-fake-answer-honesty': 'honesty',
  'borrowed-tool-damage-hide-honesty': 'honesty',
  'lab-safety-goggles-skip': 'rules',
  'stairs-jumping-two-steps': 'rules',
  'bike-lane-wrong-way': 'rules',
  'inline-skate-no-gear': 'rules',
  'emergency-exit-blocked': 'rules',
  'chemicals-mix-danger': 'rules',
  'goalpost-hanging-danger': 'rules',
  'hot-soup-running-danger': 'rules',
  'pool-diving-forbidden-zone': 'rules',
  'indoor-shoes-skip-rule': 'rules',
  'jaywalking-after-school': 'rules',
  'cutter-knife-playing-danger': 'rules',
  'elevator-overcapacity': 'rules',
  'electrical-outlet-overload': 'rules',
  'schoolbus-no-seatbelt-standing': 'rules',
  'gym-window-hanging-danger': 'rules',
  'kitchen-restricted-entry': 'rules',
  'outlet-touching-junior-danger': 'rules',
  'cliff-edge-photo-danger': 'rules',
  'self-study-sneak-out': 'rules',
  'umbrella-swinging-danger': 'rules',
  'fire-drill-horseplay': 'rules',
  'kickboard-no-helmet-fast': 'rules',
  'scissors-throwing-play': 'rules',
  'track-wrong-direction-running': 'rules',
  'earphones-loud-crossing-danger': 'rules',
  'campfire-unattended-leave': 'rules',
  'wet-floor-no-sign': 'rules',
  'rooftop-unauthorized-access': 'rules',
  'swing-standing-overswing-danger': 'rules',
  'kitchen-knife-junior-touch': 'rules',
  'window-leaning-out-danger': 'rules',
  'fire-extinguisher-play-danger': 'rules',
  'nickname-teasing-target': 'bullying',
  'sns-tag-exclusion': 'bullying',
  'team-pick-always-last': 'bullying',
  'lunch-seat-subtle-exclusion': 'bullying',
  'dialect-teasing-transferstudent': 'bullying',
  'stutter-mimicking-teasing': 'bullying',
  'group-opinion-ignored-bullying': 'bullying',
  'game-kick-low-skill-bullying': 'bullying',
  'glasses-teasing': 'bullying',
  'weight-teasing': 'bullying',
  'old-supplies-mocked': 'bullying',
  'brand-shoes-exclusion': 'bullying',
  'store-line-subtle-exclusion': 'bullying',
  'drawing-skill-mocked': 'bullying',
  'afterschool-seat-taken-exclusion': 'bullying',
  'slang-unfamiliar-teasing': 'bullying',
  'body-odor-gossip-bullying': 'bullying',
  'no-pet-teasing': 'bullying',
  'kickball-mistake-blamed-repeatedly': 'bullying',
  'hiding-belongings-prank-bullying': 'bullying',
  'groupchat-ignore-one-person': 'bullying',
  'walking-style-mimicking-teasing': 'bullying',
  'test-score-public-comparison-teasing': 'bullying',
  'artwork-secretly-damaged-bullying': 'bullying',
  'name-distortion-teasing': 'bullying',
  'anonymous-board-badmouthing': 'bullying',
  'presentation-secret-jeering': 'bullying',
  'leftover-food-public-shaming': 'bullying',
  'small-body-seat-denied': 'bullying',
  'dating-rumor-teasing': 'bullying',
  'group-assignment-repeatedly-excluded': 'bullying',
  'slow-reply-badmouthing': 'bullying',
  'changing-room-body-comment-bullying': 'bullying',
  'class-wide-mimicking-mockery': 'bullying',
  'meme-photo-edit-teasing': 'bullying',
  'accent-mimicking-teasing': 'bullying',
  'effort-belittling-teasing': 'bullying',
  'group-photo-deliberate-crop-exclusion': 'bullying',
  'wheelchair-ramp-yield': 'consideration',
  'pregnant-seat-yield': 'consideration',
  'noise-sensitive-friend-consideration': 'consideration',
  'left-handed-desk-share': 'consideration',
  'elderly-heavy-bag-help-consideration': 'consideration',
  'visually-impaired-guide-consideration': 'consideration',
  'multicultural-family-language-consideration': 'consideration',
  'hearing-impaired-classmate-consideration': 'consideration',
  'food-allergy-menu-consideration': 'consideration',
  'wheelchair-classroom-space-consideration': 'consideration',
  'stuttering-friend-listen-consideration': 'consideration',
  'religious-diet-menu-consideration': 'consideration',
  'younger-sibling-pace-consideration': 'consideration',
  'new-country-food-culture-consideration': 'consideration',
  'test-anxiety-quiet-consideration': 'consideration',
  'grieving-friend-space-consideration': 'consideration',
  'anxious-newcomer-pace-consideration': 'consideration',
  'motion-sick-carsick-consideration': 'consideration',
  'colorblind-friend-chart-consideration': 'consideration',
  'single-parent-family-topic-consideration': 'consideration',
  'wheelchair-fieldtrip-route-consideration': 'consideration',
  'diabetic-friend-snack-consideration': 'consideration',
  'anxiety-disorder-friend-consideration': 'consideration',
  'prosthetic-limb-friend-consideration': 'consideration',
  'jetlag-exchange-student-consideration': 'consideration',
  'stroller-doorway-yield-consideration': 'consideration',
  'sensory-overload-classroom-consideration': 'consideration',
  'crutches-classmate-carry-consideration': 'consideration',
  'divorced-parents-topic-consideration': 'consideration',
  'braces-eating-difficulty-consideration': 'consideration',
  'reading-disability-friend-consideration': 'consideration',
  'medication-time-schedule-consideration': 'consideration',
  'wheelchair-sports-rule-adjustment-consideration': 'consideration',
  'grandparents-tech-teach-consideration': 'consideration',
  'burn-scar-classmate-consideration': 'consideration',
  'lactose-intolerant-milk-consideration': 'consideration',
  'wheelchair-museum-exhibit-height-consideration': 'consideration',
  'group-topic-vote-disagreement': 'conflict',
  'shared-locker-space-dispute': 'conflict',
  'playlist-choice-conflict': 'conflict',
  'debate-club-opinion-clash': 'conflict',
  'shared-room-cleanup-schedule-conflict': 'conflict',
  'gift-exchange-value-conflict': 'conflict',
  'seat-swap-request-conflict': 'conflict',
  'club-leader-election-conflict': 'conflict',
  'shared-notebook-writing-disagreement': 'conflict',
  'sports-position-preference-conflict': 'conflict',
  'shared-plant-care-method-conflict': 'conflict',
  'birthday-party-guest-list-conflict': 'conflict',
  'shared-toy-turn-order-conflict': 'conflict',
  'shared-earphone-volume-conflict': 'conflict',
  'class-mascot-name-vote-conflict': 'conflict',
  'homework-help-repayment-conflict': 'conflict',
  'field-trip-buddy-pairing-conflict': 'conflict',
  'video-call-schedule-conflict': 'conflict',
  'costume-color-choice-conflict': 'conflict',
  'shared-computer-time-conflict': 'conflict',
  'shared-blanket-camp-conflict': 'conflict',
  'presentation-order-conflict': 'conflict',
  'shared-charger-priority-conflict': 'conflict',
  'team-project-deadline-blame-conflict': 'conflict',
  'shared-recipe-cooking-class-conflict': 'conflict',
  'nickname-usage-disagreement-conflict': 'conflict',
  'shared-tent-space-conflict': 'conflict',
  'class-vote-tie-conflict': 'conflict',
  'shared-basketball-court-time-conflict': 'conflict',
  'group-report-format-conflict': 'conflict',
  'shared-badminton-racket-conflict': 'conflict',
  'movie-genre-choice-conflict': 'conflict',
  'shared-picnic-spot-conflict': 'conflict',
  'shared-drawing-tablet-turn-conflict': 'conflict',
  'shared-microphone-karaoke-conflict': 'conflict',
  'shared-recess-ball-conflict': 'conflict',
  'shared-fan-summer-conflict': 'conflict',
  'movie-theater-phone-light': 'manners',
  'elevator-loud-phonecall': 'manners',
  'restaurant-running-around': 'manners',
  'public-transport-eating-smelly-food': 'manners',
  'library-shoes-on-table': 'manners',
  'swimming-pool-running-poolside': 'manners',
  'concert-hall-standing-up-blocking': 'manners',
  'restroom-line-cutting-manners': 'manners',
  'museum-flash-photography': 'manners',
  'park-bike-pedestrian-path': 'manners',
  'church-temple-loud-talking': 'manners',
  'hospital-waiting-room-noise': 'manners',
  'stadium-trash-leaving': 'manners',
  'cafe-table-hogging-manners': 'manners',
  'apartment-late-night-noise': 'manners',
  'grocery-store-touching-food': 'manners',
  'airplane-seat-reclining-manners': 'manners',
  'public-restroom-water-splash': 'manners',
  'shop-mannequin-messing': 'manners',
  'ferry-deck-leaning-over': 'manners',
  'waiting-room-shoes-on-chair': 'manners',
  'zoo-tapping-glass-teasing-animal': 'manners',
  'restaurant-loud-video-no-headphones': 'manners',
  'library-loud-group-chatting': 'manners',
  'airport-security-line-cutting': 'manners',
  'wedding-hall-running-around': 'manners',
  'shared-office-desk-messy': 'manners',
  'taxi-door-slamming': 'manners',
  'public-park-flower-picking': 'manners',
  'sauna-loud-splashing': 'manners',
  'train-station-blocking-doorway': 'manners',
  'classroom-hallway-running-manners': 'manners',
  'bank-atm-line-crowding': 'manners',
  'shared-garden-plot-trampling': 'manners',
  'photo-studio-touching-props': 'manners',
  'shared-charging-station-hogging': 'manners',
  'shared-vending-machine-shaking': 'manners',
  'campground-shared-facility-mess': 'manners',
  'shared-umbrella-stand-messing': 'manners',
  'shared-printer-hogging-manners': 'manners',
  'science-fair-team-experiment': 'teamwork',
  'class-mural-painting-together': 'teamwork',
  'relay-race-team-strategy': 'teamwork',
  'school-festival-booth-teamwork': 'teamwork',
  'orchestra-practice-together': 'teamwork',
  'cooking-class-team-roles': 'teamwork',
  'garden-harvest-teamwork': 'teamwork',
  'sports-day-tug-of-war-teamwork': 'teamwork',
  'newspaper-club-role-division': 'teamwork',
  'talent-show-group-act-practice': 'teamwork',
  'debate-team-role-assignment': 'teamwork',
  'robot-competition-team-build': 'teamwork',
  'choir-harmony-practice-teamwork': 'teamwork',
  'model-building-collaborative-project': 'teamwork',
  'field-day-relay-baton-pass-teamwork': 'teamwork',
  'book-club-discussion-teamwork': 'teamwork',
  'aquarium-fish-tank-cleaning-teamwork': 'teamwork',
  'class-flag-design-teamwork': 'teamwork',
  'science-museum-quiz-team-mission': 'teamwork',
  'class-newsletter-editing-teamwork': 'teamwork',
  'camping-trip-meal-prep-teamwork': 'teamwork',
  'class-recycling-sorting-teamwork': 'teamwork',
  'science-club-observation-log-teamwork': 'teamwork',
  'community-service-team-cleanup': 'teamwork',
  'class-vegetable-garden-planning-teamwork': 'teamwork',
  'school-broadcast-team-roles': 'teamwork',
  'school-farm-animal-care-teamwork': 'teamwork',
  'group-science-report-writing-teamwork': 'teamwork',
  'field-trip-group-schedule-planning': 'teamwork',
  'class-time-capsule-teamwork': 'teamwork',
  'class-olympic-cheer-squad-teamwork': 'teamwork',
  'library-book-fair-setup-teamwork': 'teamwork',
  'school-play-set-design-teamwork': 'teamwork',
  'class-flower-bed-teamwork': 'teamwork',
  'class-quiz-bowl-team-strategy': 'teamwork',
  'class-mock-trial-role-teamwork': 'teamwork',
  'class-recipe-book-teamwork': 'teamwork',
  'class-mural-cleanup-crew-teamwork': 'teamwork',
  'class-podcast-production-teamwork': 'teamwork',
  'class-science-experiment-cleanup-teamwork': 'teamwork',
  'class-board-game-design-teamwork': 'teamwork',
  'class-yearbook-photo-collection-teamwork': 'teamwork',
  'class-relay-quiz-team-support': 'teamwork',
}

export function groupOf(item: SituationItem): SituationGroupKey {
  return GROUP_OF[item.id] ?? 'etc'
}

export function groupSituations(items: SituationItem[]) {
  return GROUP_DEFS.map((def) => ({ def, items: items.filter((item) => groupOf(item) === def.key) })).filter(
    (g) => g.items.length > 0,
  )
}
