import type { ConversationItem } from './api'

// Conversations only carry a scene-setting sentence, not a short title, so
// known ids get a hand-picked label here. New items created later via the
// admin screen fall back to that sentence below.
const TITLES: Record<string, string> = {
  reschedule: '약속 시간 조율하기',
  celebration: '친구 소식 축하하기',
  apology: '실수 사과하기',
  'sharing-toy': '장난감 같이 쓰기',
  empathy: '아픈 강아지 위로하기',
  'keep-secret': '비밀 지키기',
  'topic-compromise': '모둠 발표 주제 의견 타협',
  'secret-slip': '비밀 누설 후 사과하기',
  'test-score-envy': '시험 점수 질투 다스리기',
  'new-hobby': '친구의 새 취미 경청하기',
  'group-role-conflict': '발표 역할 떠넘기기',
  'losing-game-graceful': '계속 지는 친구 위로하기',
  'borrowed-item-late': '빌린 책 늦게 돌려주기',
  'rumor-correction': '잘못된 소문 바로잡기',
  'exam-stress-comfort': '시험 앞둔 친구 다독이기',
  'cheating-temptation': '시험 중 답 보여달라는 부탁',
  'teamwork-praise': '밤늦게 준비해온 친구 칭찬하기',
  'exclusion-witness': '놀이에서 따돌림 목격하기',
  'screen-time-argument': '게임 시간 다투는 동생 말리기',
  'future-dream-share': '친구의 장래희망 들어주기',
  'chores-division': '집안일 분담 다투기',
  'surprise-party-plan': '깜짝 생일파티 준비하기',
  'losing-temper-apology': '화낸 뒤 사과하기',
  'new-transfer-student': '혼자인 전학생에게 다가가기',
  'environment-recycling': '분리수거 깜빡한 친구 알려주기',
  'compliment-effort': '상 못 받은 친구 노력 인정하기',
  'peer-pressure-refuse': '친구 놀리기 부추김 거절하기',
  'sports-team-loss': '시합 진 팀원 위로하기',
  'sibling-jealousy': '동생만 챙기는 것 같아 서운할 때',
  'thank-you-note': '도와준 친구에게 고마움 표현하기',
  'lost-pet-comfort': '강아지 잃어버린 친구 위로하기',
  'broken-friendship-repair': '다퉜던 친구와 화해하기',
  'group-chat-misunderstanding': '단체 채팅 오해 풀기',
  'volunteer-invite': '봉사활동 같이 가자는 권유',
  'losing-competition-fair': '대회에서 떨어진 친구 위로하기',
  'borrowing-money-refuse-politely': '돈 빌려달라는 부탁 거절하기',
  'class-election-support': '반장 선거 나간 친구 응원하기',
  'moving-away-farewell': '이사 가는 친구와 작별 인사',
  'video-game-addiction-concern': '게임에 빠진 친구 걱정하기',
  'unfair-grading-complaint': '억울한 채점에 속상한 친구 위로',
  'bragging-friend-response': '계속 자랑하는 친구 대하기',
  'helping-with-homework': '수학 숙제 도와주기',
  'weather-picnic-cancel': '소풍 취소돼 실망한 친구 달래기',
  'sharing-credit-teamwork': '발표 성과 혼자 차지하려는 친구',
  'losing-item-honesty': '주운 지갑 정직하게 처리하기',
  'body-image-comfort': '외모 놀림받은 친구 위로하기',
  'new-sibling-announcement': '동생 태어난다는 소식 들어주기',
  'project-deadline-panic': '마감 임박해 당황한 친구 돕기',
  'compliment-appearance-change': '바뀐 헤어스타일 칭찬하기',
  'giving-advice-crush': '짝사랑 고민 들어주기',
  'group-project-role-swap': '모둠 과제 역할 나누기',
  'lunch-tray-drop': '급식판 떨어뜨린 친구 돕기',
  'locker-combination-forgot': '사물함 비밀번호 잊은 친구 돕기',
  'book-recommendation': '재미있는 책 추천하기',
  'rainy-day-umbrella-share': '우산 같이 쓰자고 하기',
  'field-day-team-pick': '체육대회 팀 정하기',
  'birthday-gift-idea': '생일 선물 고민 상담하기',
  'class-pet-turn': '학급 동물 돌봄 순서 챙기기',
  'video-game-strategy': '게임 전략 상의하기',
  'moving-seat-request': '짝꿍에게 자리 바꿔달라 하기',
  'forgot-homework-teacher': '깜빡한 숙제 선생님께 말씀드리기',
  'field-trip-permission': '현장학습 신청서 문의하기',
  'computer-error-help': '컴퓨터 문제 도움 요청하기',
  'presentation-nervous': '발표 앞두고 긴장 상담하기',
  'lost-textbook-teacher': '잃어버린 교과서 문의하기',
  'extra-credit-question': '추가 점수 방법 여쭤보기',
  'seat-change-request-teacher': '자리 배치 요청하기',
  'club-activity-signup': '동아리 가입 문의하기',
  'makeup-test-request': '보충 시험 요청하기',
  'reading-recommendation-teacher': '선생님께 책 추천받기',
  'stomach-ache-doctor': '배 아파서 진료받기',
  'broken-arm-checkup': '다친 팔 진료받기',
  'allergy-checkup': '알레르기 검사받기',
  'dental-checkup': '치과에서 진료받기',
  'flu-symptoms': '독감 증상 진료받기',
  'eye-checkup': '시력 검사받기',
  'bookstore-recommendation': '서점에서 책 추천받기',
  'shoe-size-exchange': '신발 사이즈 교환하기',
  'bakery-order': '빵집에서 빵 주문하기',
  'lost-and-found-store': '가게에 두고 온 물건 찾기',
  'sporting-goods-advice': '운동용품 추천받기',
  'pet-shop-question': '애완동물 용품 문의하기',
  'parent-curfew-negotiate': '귀가 시간 부모님과 정하기',
  'sibling-toy-sharing': '장난감 두고 동생과 다투기',
  'parent-grade-report': '성적표 부모님께 보여드리기',
  'sibling-homework-help': '동생 숙제 도와주기',
  'family-trip-planning': '가족 여행 계획 상의하기',
  'parent-allowance-request': '용돈 올려달라 부탁하기',
  'sibling-room-share': '방 같이 쓰는 규칙 정하기',
  'parent-pet-request': '반려동물 키우고 싶다 조르기',
  'coach-team-strategy': '코치와 경기 작전 상의하기',
  'librarian-book-search': '사서 선생님께 책 찾아달라 하기',
  'neighbor-noise-apology': '층간소음 이웃에게 사과하기',
  'bus-driver-question': '버스 기사님께 정류장 여쭤보기',
  'vet-pet-checkup': '반려동물 건강 검진받기',
  'online-chat-misunderstanding-emoji': '단체 채팅 오해 이모티콘으로 풀기',
  'video-call-lag-emoji': '화상 수업 화면 문제 해결하기',
  'game-invite-emoji': '같이 게임하자고 초대하기',
  'online-class-question-emoji': '온라인 수업 중 질문하기',
  'social-media-comment-emoji': '친구 게시물에 이모티콘 반응하기',

  // Newer items use a "<category>-slug" id convention (see groupOf below),
  // so their titles are just listed here without needing a GROUP_OF entry.
  'community-firefighter-safety-question': '소방관님께 화재 대피 여쭤보기',
  'community-police-officer-lost-way': '길 잃고 경찰관님께 도움 요청',
  'community-mail-carrier-package': '우편배달부 아저씨와 소포 확인',
  'community-apartment-guard-missing-package': '경비 아저씨께 택배 분실 문의',
  'community-taekwondo-belt-test': '태권도 관장님과 승급 심사 상담',
  'community-management-office-playground-broken': '관리사무소에 놀이터 고장 신고',
  'community-lifeguard-pool-safety-emoji': '안전요원께 주의받고 사과하기',
  'community-newspaper-delivery-thanks-emoji': '신문 배달 아저씨께 감사 인사',
  'community-hair-salon-haircut-consult': '미용실에서 머리 스타일 상담',
  'community-dry-cleaner-stain-help': '세탁소 사장님과 얼룩 상담',
  'community-bike-repair-brake-fix': '자전거 브레이크 수리 맡기기',
  'community-bathhouse-manager-schedule': '목욕탕 이용시간 여쭤보기',
  'community-playground-guardian-safety-warning': '놀이터 안전지킴이 주의받기',
  'community-crossing-guard-traffic-safety': '횡단보도 안전 지도받기',
  'community-elevator-neighbor-greeting': '엘리베이터에서 이웃 인사',
  'community-village-bus-driver-bell-question': '마을버스 하차벨 물어보기',
  'community-subway-staff-card-recharge': '지하철 교통카드 충전 문의',
  'community-taxi-driver-destination': '택시 기사님께 목적지 말하기',
  'community-senior-center-yut-game': '경로당에서 윷놀이하기',
  'community-village-festival-signup': '마을 축제 장기자랑 신청',
  'community-woodcraft-workshop-instructor': '목공예 체험 도구함 만들기',
  'community-librarian-reading-quiz-prep': '독서 골든벨 함께 준비하기',
  'community-helpful-adult-playground-injury': '놀이터에서 다친 뒤 도움받기',
  'community-rooftop-garden-manager-plant-care': '옥상정원 식물 관리법 배우기',
  'community-center-program-signup': '방과후 요리교실 신청하기',
  'community-festival-volunteer-signup': '지역 축제 자원봉사 신청',
  'community-blood-donation-bus-volunteer': '헌혈버스 캠페인 함께하기',
  'community-animal-shelter-volunteer': '유기견 보호센터 봉사하기',
  'community-post-office-clerk-letter': '우체국에서 편지 부치기',
  'community-bank-teller-savings': '은행에서 용돈 저금 상담',
  'community-amusement-park-info-desk-lost-item': '놀이공원서 잃은 모자 찾기',
  'community-tourist-info-center-travel-question': '여행지 관광안내소 문의하기',
  'community-swim-coach-stroke-correction': '수영 자유형 자세 교정받기',
  'community-basketball-coach-shooting-practice': '농구 슛 성공하고 기뻐하기',
  'community-baseball-coach-batting-form': '야구 타격 자세 배우기',
  'community-amusement-park-info-desk-lost-parent': '놀이공원서 부모님 잃어버림',
  'community-subway-staff-lost-parent-help': '지하철서 엄마 놓치고 도움청함',
  'community-park-bench-elder-janggi': '공원에서 장기 배우기',
  'community-carpenter-chair-repair': '목수 아저씨께 의자 수리 부탁',
  'community-museum-docent-exhibit-question': '박물관에서 유물 질문하기',
  'community-zoo-keeper-animal-question': '동물원서 기린 이야기 듣기',
  'community-aquarium-staff-question': '수족관서 상어 질문하기',
  'community-recycling-center-staff': '재활용센터서 분리수거 배우기',
  'community-library-book-return-overdue': '도서관 책 연체 사과하기',
  'community-mountain-trail-guide': '등산로 안내원께 코스 문의',
  'community-neighborhood-watch-volunteer': '방범대 아저씨께 안전 조언',
  'community-national-park-camping-question': '국립공원 캠핑장 예약 문의',
  'community-ice-rink-staff-skate-rental': '스케이트장서 스케이트 대여',
  'community-badminton-coach-serve-practice': '배드민턴 서브 성공하기',
  'community-village-choir-director': '합창단서 발성 교정받기',
  'community-cooking-class-instructor': '요리교실서 오므라이스 완성',
  'family-allowance-negotiate': '용돈 인상 협상하기',
  'family-sibling-fight-makeup': '동생과 다툰 뒤 화해하기',
  'family-chores-schedule': '집안일 당번표 정하기',
  'family-trip-destination-vote': '가족여행지 함께 정하기',
  'family-report-card-share': '성적표 부모님께 보여드리기',
  'family-pet-request-hamster': '햄스터 기르고 싶다고 조르기',
  'family-helping-sibling-homework': '동생 숙제 도와주기',
  'family-bedtime-rule-talk': '취침 시간 정하기',
  'family-screen-time-negotiate': '스크린타임 규칙 정하기',
  'family-holiday-prep-help': '명절 준비 함께 돕기',
  'family-grandma-phone-call': '할머니께 안부 전화드리기',
  'family-moving-house-news': '이사 소식 듣고 이야기하기',
  'family-birthday-party-plan': '동생 생일파티 준비하기',
  'family-future-dream-talk': '장래희망 부모님께 말씀드리기',
  'family-camping-prep': '캠핑 준비물 챙기기',
  'family-house-meeting-rules': '가족회의에서 규칙 정하기',
  'family-dinner-while-parents-late': '부모님 야근 중 저녁 챙기기',
  'family-cousin-visit': '사촌 방문 준비하기',
  'family-vet-bill-talk': '반려견 병원비 상의하기',
  'family-housewarming-prep': '집들이 준비 돕기',
  'family-broke-rule-reflect': '약속 어긴 것 반성하기',
  'family-friend-trouble-advice': '친구 문제 부모님께 상담하기',
  'family-photo-day': '가족사진 촬영일',
  'family-allowance-ledger': '용돈기입장 함께 쓰기',
  'family-parent-health-worry': '아빠 건강 걱정하기',
  'family-shared-room-rules': '형과 방 같이 쓰는 규칙 정하기',
  'family-errand-for-allowance': '심부름하고 용돈 벌기',
  'family-console-turn-dispute': '게임기 순서 다투기',
  'family-grandpa-gift-idea': '할아버지 생신 선물 고민하기',
  'family-dinner-menu-vote': '가족 저녁 메뉴 정하기',
  'family-mom-surprise-party': '엄마 생신 깜짝파티 준비',
  'family-bike-ride-promise': '아빠와 자전거 타기 약속',
  'family-sibling-borrowed-without-asking': '동생이 물건 몰래 써서 속상함',
  'family-vacation-plan-together': '방학 계획 함께 짜기',
  'family-spending-rule-talk': '용돈 사용처 정하기',
  'family-wedding-attend-cousin': '이모 결혼식 참석 준비',
  'family-catch-ball-with-dad': '아빠와 캐치볼 하며 고민 나누기',
  'family-grandma-house-sleepover': '할머니 댁에서 하룻밤 자기',
  'family-weekend-cleanup': '가족 대청소하는 날',
  'family-lost-at-amusement-park': '놀이공원에서 부모님을 잃어버림',
  'family-reunited-after-lost-relief': '잃어버렸다가 다시 만난 안도감',
  'family-sibling-award-celebrate-emoji': '동생 그림대회 수상 축하하기',
  'family-new-neighbor-greet-emoji': '이사 온 이웃과 첫인사',
  'teacher-math-homework-help': '수학 숙제 질문하기',
  'teacher-korean-score-drop-worry': '국어 점수 상담하기',
  'teacher-presentation-slide-check': '발표 자료 점검받기',
  'teacher-science-club-join': '과학 동아리 가입 문의',
  'teacher-career-dream-talk': '장래희망 이야기 나누기',
  'teacher-phone-rule-reminder-emoji': '휴대폰 규칙 지키기',
  'teacher-transfer-student-buddy': '전학생 짝꿍 되어주기',
  'teacher-exam-study-method': '시험공부 방법 여쭤보기',
  'teacher-after-school-coding-class': '방과후 코딩 수업 신청',
  'teacher-picky-eating-lunch': '편식 고민 상담하기',
  'teacher-friend-conflict-advice': '친구와 다툰 고민 상담',
  'teacher-lost-gym-clothes': '체육복 분실 문의하기',
  'teacher-late-arrival-apology-emoji': '지각하고 사과하기',
  'teacher-notice-book-missed': '알림장 빠뜨려서 확인하기',
  'teacher-cleaning-duty-swap': '청소 당번 교체 부탁',
  'teacher-talent-show-role-emoji': '학예회 역할 배정받기',
  'teacher-sports-day-relay-emoji': '계주 대표 선수 되기',
  'teacher-mystery-book-recommend': '추리소설 추천받기',
  'teacher-drawing-talent-praise-emoji': '그림 재능 칭찬받기',
  'teacher-volunteer-hours-question': '봉사활동 시간 문의하기',
  'teacher-class-meeting-agenda': '학급회의 안건 제안하기',
  'teacher-seat-front-vision': '시력 때문에 자리 앞으로',
  'teacher-art-supplies-question': '미술 준비물 문의하기',
  'teacher-tablet-trouble-emoji': '태블릿 오류 해결받기',
  'teacher-writing-contest-signup': '글짓기 대회 참가 신청',
  'teacher-vacation-homework-plan': '방학 숙제 계획 상담',
  'teacher-counseling-appointment': '고민 상담 시간 예약하기',
  'teacher-talking-in-class-apology-emoji': '수업 중 떠들어서 사과하기',
  'teacher-class-library-donate': '학급문고 책 기부하기',
  'teacher-class-motto-suggestion': '학급 급훈 제안하기',
  'teacher-earthquake-drill-question': '지진 대피 훈련 질문하기',
  'teacher-parent-message-relay': '부모님께 전할 말 여쭤보기',
  'teacher-singing-talent-encourage-emoji': '노래 실력 격려받기',
  'teacher-exam-anxiety-comfort-emoji': '시험 전날 긴장 달래기',
  'teacher-self-intro-nervous-emoji': '자기소개 준비하며 긴장하기',
  'teacher-class-election-support-emoji': '학급 임원 선거 출마 상담',
  'teacher-seatmate-change-request-emoji': '짝 바꿔달라 부탁하기',
  'teacher-presentation-order-swap': '발표 순서 바꿔달라 부탁',
  'teacher-science-assessment-question': '과학 수행평가 방법 문의',
  'teacher-classroom-plant-duty': '교실 화분 물주기 당번',
  'teacher-forgot-art-supplies': '미술 준비물 안 가져와서 빌리기',
  'teacher-forgot-recorder-music-class': '리코더 놓고 와서 상담하기',
  'teacher-after-school-question-relief-emoji': '방과후 남아서 질문하기',
  'teacher-reading-log-check': '독서기록장 검사받기',
  'hospital-ear-infection-checkup': '귀 아파서 이비인후과 진료',
  'hospital-atopy-skin-clinic': '피부과에서 아토피 상담',
  'hospital-wrist-sprain-ortho': '정형외과에서 손목 삠 진료',
  'hospital-stye-eye-clinic': '안과에서 다래끼 진료',
  'hospital-worry-counseling-center': '상담센터에서 걱정 이야기',
  'hospital-vaccination-nervous-emoji': '예방접종 전 긴장한 마음',
  'hospital-burn-minor-er': '응급실에서 가벼운 화상 치료',
  'hospital-xray-explanation': '엑스레이 촬영 설명 듣기',
  'hospital-physical-therapy-knee': '물리치료실에서 무릎 재활',
  'hospital-height-nutrition-consult': '영양상담에서 키 크는 법 문의',
  'hospital-hearing-test': '청력검사 받으러 가기',
  'hospital-food-poisoning-relief-emoji': '배탈 나은 후 안도감',
  'hospital-headache-checkup': '두통 상담받기',
  'hospital-allergy-result-explanation': '알레르기 재검사 결과 듣기',
  'hospital-tonsillitis-checkup': '편도염으로 목 진료받기',
  'hospital-sinusitis-nose-checkup': '축농증으로 코 진료받기',
  'hospital-athletes-foot-checkup': '무좀으로 발 진료받기',
  'hospital-nosebleed-checkup': '코피 나서 진료받기',
  'hospital-finger-cut-treatment': '손가락 베인 상처 치료',
  'hospital-sleep-problem-consult': '잠 못 자는 문제 상담',
  'hospital-oriental-medicine-acupuncture': '한의원에서 침 맞기',
  'hospital-eyeglasses-prescription': '안경 도수 맞추러 가기',
  'hospital-cavity-dental-filling': '충치 치료받기',
  'hospital-post-surgery-checkup-relief-emoji': '편도 수술 후 회복 확인',
  'hospital-frostbite-prevention-winter': '겨울철 동상 예방 안내',
  'hospital-heatstroke-prevention-summer': '여름철 열사병 예방 상담',
  'hospital-picky-eating-nutrition': '편식 걱정 영양상담',
  'hospital-mri-explanation': 'MRI 촬영 전 설명 듣기',
  'hospital-sleep-endoscopy-prep': '수면내시경 전 안내받기',
  'hospital-rehab-after-cast': '깁스 푼 후 재활치료',
  'hospital-gratitude-to-doctor-emoji': '치료해주신 의사선생님께 감사',
  'hospital-scoliosis-posture-checkup': '자세 검사로 척추 진료받기',
  'hospital-motion-sickness-consult': '멀미 심한 것 상담받기',
  'hospital-growth-plate-checkup': '성장판 검사받기',
  'hospital-splinter-removal': '가시 박힌 손 치료받기',
  'hospital-earwax-removal': '귀지 제거 진료받기',
  'hospital-checkup-result-good-news-emoji': '건강검진 결과 듣고 안심',
  'hospital-cast-application': '팔 깁스 새로 받기',
  'hospital-swallowed-object-checkup': '작은 물건 삼켜서 검사받기',
  'hospital-swimmers-ear': '수영 후 외이도염 진료',
  'hospital-anxiety-before-shot-emoji': '주사 맞기 전 무서운 마음',
  'hospital-fever-checkup': '고열로 소아과 진료받기',
  'hospital-braces-orthodontics': '치아 교정 상담받기',
  'hospital-conjunctivitis-checkup': '눈병으로 안과 진료받기',
  'hospital-warts-removal': '손에 난 사마귀 치료받기',
  'hospital-recovery-thanks-nurse-emoji': '간호사 선생님께 감사 인사',
  'hospital-scar-treatment-consult': '흉터 치료 상담받기',
  'hospital-asthma-checkup': '천식으로 호흡기 진료받기',
  'store-stationery-eraser-recommend': '문구점서 지우개 추천받기',
  'store-mart-checkout-barcode-error': '마트서 바코드 오류 확인',
  'store-toy-shop-assembly-help': '장난감 조립법 물어보기',
  'store-optician-lens-recheck': '안경점서 시력 재검사',
  'store-hair-salon-style-consult': '미용실서 머리스타일 상담',
  'store-laundry-drop-off': '세탁소에 교복 맡기기',
  'store-bike-shop-repair-request': '자전거가게서 체인 수리 요청',
  'store-bike-shop-new-bike-consult': '자전거가게서 새 자전거 상담',
  'store-music-shop-recorder-recommend': '악기점서 리코더 추천받기',
  'store-photo-studio-id-photo': '사진관서 증명사진 문의',
  'store-flower-shop-parents-day-gift': '꽃집서 어버이날 선물 고르기',
  'store-fruit-shop-seasonal-recommend': '과일가게서 제철 과일 추천',
  'store-tteokbokki-order': '분식점서 떡볶이 주문',
  'store-cafe-drink-order': '카페서 초콜릿 음료 주문',
  'store-game-shop-used-game-inquiry': '게임샵서 중고게임 문의',
  'store-comic-rental-shop': '만화방서 만화책 대여',
  'store-market-haggling-fruit': '시장서 과일값 흥정하기',
  'store-clothes-refund-wrong-size': '옷가게서 사이즈 환불 요청',
  'store-exchange-different-color': '필통 색깔 교환 요청',
  'store-gift-wrap-request': '생일선물 포장 요청하기',
  'store-coupon-points-question': '포인트 사용 문의하기',
  'store-sold-out-restock-inquiry': '품절 필통 입고 문의',
  'store-sale-schedule-question': '운동화 세일 기간 문의',
  'store-membership-signup': '문구점 회원가입 안내받기',
  'store-receipt-reissue-request': '영수증 재발행 요청하기',
  'store-durable-pencil-case-recommend': '튼튼한 필통 추천받기',
  'store-secondhand-toy-sell': '중고거래매장에 장난감 팔기',
  'store-hair-salon-booking-vacation': '방학 전 미용실 예약하기',
  'store-convenience-store-find-item': '편의점서 물건 위치 찾기',
  'store-stationery-gift-for-friend': '친구 생일선물 문구 고르기',
  'store-bookstore-reserve-next-volume': '서점서 다음 권 예약하기',
  'store-bakery-allergy-ingredients': '빵집서 알레르기 성분 문의',
  'store-shoe-shop-lace-color-choice': '운동화 끈 색깔 고르기',
  'store-toy-shop-other-branch-inquiry': '다른 지점 재고 문의하기',
  'store-lost-parent-help-desk': '백화점서 부모님 찾기 도움요청',
  'store-ice-cream-flavor-soldout-emoji': '아이스크림 맛 품절 아쉬움',
  'store-mart-tasting-corner-emoji': '마트 시식코너서 맛보기',
  'store-toy-shop-found-favorite-emoji': '찾던 장난감 발견 기쁨',
  'store-tteokbokki-spicy-surprise-emoji': '매운 떡볶이 먹고 놀람',
  'store-stationery-cute-pencilcase-emoji': '예쁜 필통 발견 설렘',
  'store-cafe-waiting-bored-emoji': '음료 기다리며 지루함',
  'store-bike-shop-new-bike-excited-emoji': '새 자전거 받고 신남',
  'store-optician-new-glasses-awkward-emoji': '새 안경 써보고 어색함',
  'store-laundry-clean-clothes-satisfied-emoji': '깨끗해진 옷 보고 만족',
  'store-music-shop-favorite-instrument-emoji': '좋아하는 악기 발견 흥분',
  'store-photo-studio-good-photo-emoji': '사진 잘 나와서 만족',
  'store-flower-shop-pretty-flower-emoji': '예쁜 꽃 보고 설렘',
  'store-fruit-shop-free-sample-emoji': '시식용 과일 먹고 만족',
  'store-game-shop-new-release-excited-emoji': '신작 게임 발견 흥분',
  'online-game-invite-team': '온라인 게임 팀 초대하기',
  'online-video-call-background': '화상통화 배경화면 자랑',
  'online-chat-etiquette-reminder': '채팅 예절 함께 정하기',
  'online-sns-comment-praise': 'SNS 그림에 댓글 반응',
  'online-exam-good-news-emoji': '시험 잘 봤다는 소식 반응',
  'online-book-club-schedule': '온라인 독서모임 시간 정하기',
  'online-drawing-contest-encourage': '그림대회 도전 응원하기',
  'online-meeting-schedule-conflict': '화상회의 시간 조율하기',
  'online-survey-request': '온라인 설문 참여 부탁하기',
  'online-youtube-share': '재미있는 영상 공유하기',
  'online-birthday-online-emoji': '채팅방 생일 축하하기',
  'online-game-rank-up-emoji': '게임 랭킹 상승 축하하기',
  'online-wifi-lag-notice': '화상 수업 접속 문제 알리기',
  'online-streaming-reaction': '온라인 방송 같이 보기',
  'online-quiz-contest-invite': '온라인 퀴즈대회 같이 나가기',
  'online-chatroom-rules': '단체 채팅방 규칙 정하기',
  'online-class-vote-election': '온라인 반대표 투표하기',
  'online-collab-doc-work': '실시간 협업 문서 작업하기',
  'online-product-review-share': '온라인 구매 후기 공유하기',
  'online-video-challenge-invite': '영상 챌린지 같이 하기',
  'online-safety-stranger-friend': '온라인 개인정보 조심하기',
  'online-spam-block-tip': '스팸 차단 방법 알려주기',
  'online-mic-etiquette-class': '화상 수업 마이크 예절 알리기',
  'online-game-teammate-encourage': '게임 실수한 팀원 격려하기',
  'online-groupchat-misunderstanding-tone': '채팅 말투 오해 풀기',
  'online-birthday-party-invite': '화상 생일파티 초대하기',
  'online-class-late-join-apology': '온라인 수업 지각 사과하기',
  'online-video-call-noise-apology': '화상통화 소음 사과하기',
  'online-drawing-collab-suggestion': '온라인 그림 협업 제안하기',
  'online-game-item-trade': '게임 아이템 교환 제안하기',
  'online-reading-report-share': '온라인 독후감 공유하기',
  'online-class-board-notice-check': '학급 게시판 공지 확인하기',
  'online-recorder-practice-share': '리코더 연습 영상 공유하기',
  'online-talent-show-rehearsal': '학예회 리허설 일정 맞추기',
  'online-puppy-photo-share': '강아지 사진 공유하기',
  'online-refuse-gossip-chat': '단체 채팅 험담 거절하기',
  'online-coding-class-question': '온라인 코딩 수업 질문하기',
  'online-videocall-filter-joke': '화상통화 필터 장난치기',
  'online-game-rule-break-friend': '게임 반칙 친구 타이르기',
  'online-sns-profile-photo-praise': 'SNS 프로필 사진 칭찬하기',
  'online-grade-privacy-agreement': '시험 점수 비공개 약속하기',
  'online-group-deadline-reminder': '모둠 과제 마감 알려주기',
  'online-birthday-song-video-share': '생일축하 영상 함께 만들기',
  'online-presentation-order-decide': '모둠 발표 순서 정하기',
  'online-game-item-gift': '게임 아이템 선물하기',
  'online-emoji-spam-request': '이모티콘 도배 자제 부탁하기',
  'online-reading-cert-photo-share': '독서 인증 사진 공유하기',
  'online-videocall-reconnect-slow-net': '화상통화 재연결하기',
  'online-drawing-contest-result-emoji': '그림대회 입상 축하하기',
  'online-groupchat-invite-thanks-emoji': '전학생 채팅방 초대 감사',

  'travel-airport-checkin-luggage-weight': '공항 수하물 무게 초과 문의',
  'travel-airport-security-liquids-check': '보안검색대 액체류 규정 문의',
  'travel-flight-attendant-meal-choice': '기내식 메뉴 선택하기',
  'travel-flight-attendant-motion-sickness': '비행기 멀미 도움 요청',
  'travel-turbulence-companion-comfort-emoji': '비행기 흔들림에 놀란 마음',
  'travel-train-ticket-seat-confusion': '기차 좌석 번호 확인하기',
  'travel-train-conductor-wrong-seat': '기차에서 자리 잘못 앉음',
  'travel-hotel-checkin-early-request': '호텔 조기 체크인 요청',
  'travel-hotel-extra-towel-request': '호텔에 여분 수건 요청',
  'travel-hotel-wifi-password': '호텔 와이파이 비밀번호 문의',
  'travel-tour-guide-itinerary-question': '여행 가이드께 일정 문의',
  'travel-tour-guide-photo-spot-recommend': '여행 가이드께 사진 명소 추천',
  'travel-fellow-traveler-train-chat': '기차에서 만난 여행객과 대화',
  'travel-local-resident-landmark-directions': '현지 주민께 명소 길 여쭤보기',
  'travel-foreign-tourist-subway-help-korea': '외국인 관광객 지하철 안내하기',
  'travel-foreign-tourist-hanbok-rental-question': '외국인 관광객께 한복 대여점 안내',
  'travel-customs-officer-declare-item': '세관에서 신고 물품 안내받기',
  'travel-restaurant-unfamiliar-food-order': '현지 식당서 낯선 음식 주문',
  'travel-souvenir-shop-haggle-price': '기념품 가게서 가격 흥정하기',
  'travel-souvenir-shop-family-gift-choice': '가족 선물로 기념품 고르기',
  'travel-timezone-call-grandma-confusion': '시차 때문에 통화 시간 헷갈림',
  'travel-jetlag-companion-notice-sleepy-emoji': '시차 적응으로 졸린 마음',
  'travel-packing-list-friend-discussion': '여행 짐 목록 함께 확인하기',
  'travel-itinerary-planning-vote': '여행 일정 함께 정하기',
  'travel-homestay-host-greeting': '홈스테이 호스트와 첫인사',
  'travel-beach-resort-snorkel-rental': '해변 리조트서 스노클 장비 대여',
  'travel-ski-resort-equipment-rental': '스키장서 장비 대여받기',
  'travel-amusement-park-abroad-fastpass-question': '해외 놀이공원 패스트패스 문의',
  'travel-museum-abroad-audioguide-rental': '해외 박물관 오디오가이드 대여',
  'travel-language-barrier-gesture-order': '말이 안 통해 손짓으로 주문하기',
  'travel-airport-lost-luggage-counter': '공항 수하물 분실 신고하기',
  'travel-flight-delay-waiting-companion': '비행 지연 중 친구와 기다리기',
  'travel-camping-trip-tent-setup-friend': '캠핑장서 친구와 텐트 치기',
  'travel-road-trip-car-sickness-friend': '자동차 여행 중 멀미 이야기',
  'travel-travel-journal-sharing-friend': '여행 일기 함께 나눠 쓰기',
  'travel-postcard-writing-to-friend': '친구에게 엽서 써서 보내기',
  'travel-photo-taking-request-stranger': '낯선 여행객께 사진 부탁하기',
  'travel-hiking-trail-companion-encourage': '등산길에서 친구 응원하기',
  'travel-campfire-story-sharing-emoji': '캠프파이어서 이야기 나누기',
  'travel-night-market-food-tour': '야시장서 길거리 음식 투어',
  'travel-temple-stay-etiquette-question': '사찰 체험 예절 문의하기',
  'travel-island-ferry-schedule-question': '섬 여행 페리 시간표 문의',
  'travel-airport-departure-goodbye-emoji': '여행 마치고 아쉬운 작별인사',
  'travel-returning-home-relief-emoji': '집에 도착해 느끼는 편안함',
  'travel-trying-new-food-reaction-emoji': '낯선 음식 맛보고 놀란 반응',
  'travel-amazing-view-reaction-emoji': '멋진 풍경 보고 감탄하기',
  'travel-missed-bus-frustration-emoji': '버스 놓쳐서 속상한 마음',
  'travel-hotel-donotdisturb-sign-emoji': '호텔서 낮잠 자기 전 편안함',
  'travel-cruise-ocean-view-emoji': '크루즈서 처음 본 바다 전망',
  'travel-cable-car-thrill-emoji': '케이블카 타고 느낀 짜릿함',
  'travel-waterpark-slide-fun-emoji': '워터파크 미끄럼틀 타고 신남',
  'travel-bus-terminal-caught-in-time-emoji': '환승버스 겨우 탄 안도감',
  'travel-currency-exchange-first-purchase-emoji': '환전한 돈으로 첫 쇼핑 성공',
  'travel-homestay-room-cozy-emoji': '홈스테이 방에서 느낀 편안함',
  'travel-passport-new-stamp-emoji': '여권에 새 도장 받고 신기함',
  'sports-soccer-missed-shot-encourage': '슛 놓친 팀원 격려하기',
  'sports-basketball-foul-apology': '농구 파울 후 사과하기',
  'sports-baseball-lost-game-handshake': '야구 경기 후 악수하기',
  'sports-volleyball-serve-nerves': '배구 서브 앞두고 긴장 달래기',
  'sports-dodgeball-out-consoling': '피구 아웃된 친구 위로하기',
  'sports-badminton-close-call-referee': '배드민턴 판정 여쭤보기',
  'sports-table-tennis-win-gracious': '탁구 이기고 배려하기',
  'sports-swimming-personal-best-loss-emoji': '수영 시합에서 지고도 기록 축하',
  'sports-relay-baton-drop-recover': '계주 배턴 놓친 뒤 격려받기',
  'sports-taekwondo-sparring-respect-bow': '태권도 대련 후 인사 예절',
  'sports-tugofwar-team-cheer': '줄다리기 팀 응원하기',
  'sports-teeball-first-hit-excited-emoji': '티볼 첫 안타 치고 신나기',
  'sports-soccer-pk-miss-comfort': '승부차기 실패한 친구 위로',
  'sports-basketball-freethrow-nervous-emoji': '자유투 앞두고 긴장하기',
  'sports-opponent-good-play-praise': '상대팀 멋진 플레이 칭찬하기',
  'sports-teammate-wont-pass-ball': '공 안 주는 팀원과 이야기하기',
  'sports-injury-teammate-concern-emoji': '다친 팀원 걱정하기',
  'sports-pregame-nerves-share': '경기 전 긴장 나누기',
  'sports-tiebreaker-rule-question': '동점 상황 규칙 여쭤보기',
  'sports-benched-support-team-emoji': '벤치에서도 팀 응원하기',
  'sports-draw-game-discuss': '무승부 경기 소감 나누기',
  'sports-mvp-announcement-happy-emoji': 'MVP 발표 듣고 기뻐하기',
  'sports-losing-streak-encourage': '연패 중인 팀 서로 격려하기',
  'sports-captain-position-assign': '주장이 포지션 정해주기',
  'sports-hot-headed-teammate-calm': '화난 팀원 진정시키기',
  'sports-first-timer-encourage': '처음 참가한 친구 격려하기',
  'sports-post-match-interview-reflect': '경기 후 소감 나누기',
  'sports-cheerleader-thanks': '응원해준 친구들에게 감사',
  'sports-soccer-own-goal-comfort': '자책골 넣은 친구 위로하기',
  'sports-basketball-buzzer-beater-excited-emoji': '극적인 버저비터 성공 기뻐하기',
  'sports-volleyball-block-success-praise': '블로킹 성공 팀원 칭찬하기',
  'sports-baseball-strikeout-encourage': '삼진 아웃당한 친구 격려하기',
  'sports-athletics-relay-final-lap-nervous-emoji': '계주 마지막 주자 긴장 나누기',
  'sports-swimming-lane-mixup-apology': '수영 레인 착각 사과하기',
  'sports-badminton-doubles-partner-strategy': '배드민턴 복식 작전 상의',
  'sports-table-tennis-lost-serve-count-dispute': '탁구 서브 순서 확인하기',
  'sports-dodgeball-catch-save-celebrate-emoji': '피구 캐치 성공 기뻐하기',
  'sports-soccer-red-card-teammate-support': '퇴장당한 팀원 다독이기',
  'sports-basketball-substitute-in-nervous': '교체 투입되어 긴장하기',
  'sports-marathon-finish-line-cheer-emoji': '마라톤 완주 응원하기',
  'sports-longjump-personal-record-celebrate-emoji': '멀리뛰기 자기 기록 경신 기뻐하기',
  'sports-soccer-captain-armband-honor': '주장 완장 맡아서 다짐하기',
  'sports-basketball-technical-foul-calm-down': '기술 파울 후 마음 가라앉히기',
  'sports-volleyball-set-toss-miscommunication': '세트 토스 실수 이야기하기',
  'sports-badminton-shuttle-out-call-dispute': '셔틀콕 아웃 판정 이의제기',
  'sports-teeball-error-forgive-teammate': '실책한 팀원 용서하기',
  'sports-swimming-relay-anchor-pressure-emoji': '계영 마지막 주자 부담 나누기',
  'sports-soccer-handshake-line-sportsmanship': '경기 후 악수 라인 인사',
  'sports-basketball-court-time-share': '코트 시간 나눠쓰기 상의',
  'sports-athletics-baton-pass-practice': '계주 배턴 연습 상의',
  'sports-tabletennis-win-humble-emoji': '탁구 이기고 겸손하게 행동하기',
  'sports-volleyball-teammate-apology-miss': '리시브 실수 사과하기',
  'sports-soccer-goalkeeper-save-praise-emoji': '골키퍼 선방 칭찬하기',
  'sports-dodgeball-team-strategy-huddle': '피구 작전타임 상의하기',
  'sports-basketball-championship-win-joy-emoji': '결승전 우승 기쁨 나누기',
  'stranger-ask-way-follow': '길안내 핑계 따라오라기 거절',
  'stranger-lost-puppy-help': '강아지 찾기 부탁 거절하기',
  'stranger-mom-sick-lure': '엄마 아프다는 거짓말 거절',
  'stranger-candy-gift-offer': '사탕 유혹 거절하기',
  'stranger-car-ride-home-offer': '차로 데려다준다는 제안 거절',
  'stranger-photo-model-offer': '사진 모델 제안 거절하기',
  'stranger-survey-personal-info': '설문조사 개인정보 거절하기',
  'stranger-celebrity-pretend-friendly': '유명인 친한 척 거리두기',
  'stranger-academy-pickup-lie': '학원서 보냈다는 거짓말 거절',
  'stranger-just-talk-detain': '잠깐 얘기하자며 붙잡기 거절',
  'stranger-heavy-bag-help': '짐 들어달라는 부탁 거절',
  'stranger-stray-cat-feed-help': '길고양이 밥주기 도움 거절',
  'stranger-new-neighbor-house-tour': '집 구경시켜달라기 거절',
  'stranger-phone-borrow-request': '휴대폰 빌려달라기 거절하기',
  'stranger-ice-cream-treat-lure': '아이스크림 사준다는 유혹 거절',
  'stranger-mom-friend-pretend': '엄마 친구 사칭 거짓말 거절',
  'stranger-agency-scout-offer': '연예기획사 캐스팅 제안 거절',
  'stranger-survey-gift-card': '설문 참여 상품권 유혹 거절',
  'stranger-car-load-help': '차에 짐 옮기기 도움 거절',
  'stranger-playground-lonely-approach': '혼자 노는 아이에게 접근 거절',
  'stranger-delivery-door-open': '택배기사 사칭 문 열어달라기 거절',
  'stranger-elevator-follow-lure': '엘리베이터 동승 유인 거절',
  'stranger-parent-coworker-urgent': '부모님 회사동료 사칭 거절',
  'stranger-money-borrow-approach': '돈 빌려달라는 접근 거절',
  'stranger-online-friend-meetup': '온라인 친구 실제만남 요청 거절',
  'stranger-alley-shortcut-lure': '골목 지름길 안내 유인 거절',
  'stranger-injured-cat-lure': '다친 고양이 핑계 외진곳 유인 거절',
  'stranger-lost-way-map-lure': '지도 봐달라며 붙잡기 거절',
  'stranger-afterschool-pickup-lie': '방과후 데리러왔다는 거짓말 거절',
  'stranger-magic-show-lure': '마술쇼 보여준다는 유인 거절',
  'stranger-cultural-voucher-survey': '문화상품권 설문 유인 거절',
  'stranger-photographer-shoot-offer': '사진작가 화보 제안 거절하기',
  'stranger-idol-trainee-offer': '아이돌 연습생 제안 거절하기',
  'stranger-package-receive-hallway': '복도서 택배 대신받기 거절',
  'stranger-free-ticket-amusement-park': '놀이공원 무료입장권 유혹 거절',
  'stranger-hurt-animal-remote-lure': '다친 동물 핑계 유인 거절',
  'stranger-police-help-request': '경찰관께 도움요청 후 안도감',
  'stranger-store-clerk-help-request': '편의점 직원께 도움요청하기',
  'stranger-another-parent-help': '다른 부모님께 도움요청하기',
  'stranger-tell-parent-praised': '부모님께 말씀드리고 칭찬받기',
  'stranger-school-safety-lesson-recap': '안전교육 후 대처법 다짐하기',
  'stranger-teacher-teach-method-proud': '선생님께 배우고 뿌듯해하기',
  'stranger-sibling-advice-comfort': '언니의 대처법 조언에 안심하기',
  'stranger-safety-house-visit': '아동안전지킴이집 방문하기',
  'stranger-emergency-contact-plan': '비상연락 약속 함께 정하기',
  'stranger-guard-help-resolved': '경비 아저씨께 도움요청 해결',
  'stranger-walk-together-promise': '등하교 친구와 함께 다니기 약속',
  'stranger-safety-bell-use': '안전벨 사용법 배우기',
  'stranger-safe-return-service': '안심귀가서비스 알아보기',
  'stranger-parent-pickup-relief': '도움요청 후 부모님이 데리러옴',
  'stranger-handled-well-teacher-praise': '대처 잘해서 선생님께 칭찬받기',
  'stranger-friend-share-scary-experience': '친구의 무서웠던 경험 위로하기',
  'stranger-police-station-location-learn': '동네 파출소 위치 알아두기',
  'stranger-location-share-app-learn': '위치공유 앱 사용법 배우기',
  'stranger-no-personal-info-pledge': '개인정보 안 알려주기 다짐하기',
}

export function titleOf(item: ConversationItem): string {
  return TITLES[item.id] ?? item.situation
}

export type ConversationGroupKey =
  | 'friend'
  | 'family'
  | 'teacher'
  | 'hospital'
  | 'store'
  | 'online'
  | 'community'
  | 'travel'
  | 'sports'
  | 'stranger'

export const GROUP_DEFS: { key: ConversationGroupKey; label: string; emoji: string }[] = [
  { key: 'friend', label: '친구와의 대화', emoji: '👫' },
  { key: 'family', label: '가족과의 대화', emoji: '👨‍👩‍👧' },
  { key: 'teacher', label: '선생님과의 대화', emoji: '🍎' },
  { key: 'hospital', label: '병원에서의 대화', emoji: '🏥' },
  { key: 'store', label: '가게에서의 대화', emoji: '🏪' },
  { key: 'online', label: '온라인 대화', emoji: '📱' },
  { key: 'community', label: '마을 어른과의 대화', emoji: '🧑‍🤝‍🧑' },
  { key: 'travel', label: '여행지에서의 대화', emoji: '✈️' },
  { key: 'sports', label: '운동경기에서의 대화', emoji: '⚽' },
  { key: 'stranger', label: '낯선 사람과의 대화', emoji: '🛡️' },
]

// Conversation ids don't carry the counterpart/place of the exchange, so
// each one is hand-assigned here based on its scene-setting sentence.
// Anything not listed (including future admin-created items) falls back to
// the 'friend' bucket, which is also where most existing content lives.
const GROUP_OF: Record<string, ConversationGroupKey> = {
  'parent-curfew-negotiate': 'family',
  'sibling-toy-sharing': 'family',
  'parent-grade-report': 'family',
  'sibling-homework-help': 'family',
  'family-trip-planning': 'family',
  'parent-allowance-request': 'family',
  'sibling-room-share': 'family',
  'parent-pet-request': 'family',
  'new-sibling-announcement': 'family',
  'sibling-jealousy': 'family',
  'chores-division': 'family',
  'screen-time-argument': 'family',

  'forgot-homework-teacher': 'teacher',
  'field-trip-permission': 'teacher',
  'computer-error-help': 'teacher',
  'presentation-nervous': 'teacher',
  'lost-textbook-teacher': 'teacher',
  'extra-credit-question': 'teacher',
  'seat-change-request-teacher': 'teacher',
  'club-activity-signup': 'teacher',
  'makeup-test-request': 'teacher',
  'reading-recommendation-teacher': 'teacher',
  'online-class-question-emoji': 'teacher',

  'stomach-ache-doctor': 'hospital',
  'broken-arm-checkup': 'hospital',
  'allergy-checkup': 'hospital',
  'dental-checkup': 'hospital',
  'flu-symptoms': 'hospital',
  'eye-checkup': 'hospital',
  'vet-pet-checkup': 'hospital',

  'bookstore-recommendation': 'store',
  'shoe-size-exchange': 'store',
  'bakery-order': 'store',
  'lost-and-found-store': 'store',
  'sporting-goods-advice': 'store',
  'pet-shop-question': 'store',

  'group-chat-misunderstanding': 'online',
  'online-chat-misunderstanding-emoji': 'online',
  'video-call-lag-emoji': 'online',
  'game-invite-emoji': 'online',
  'social-media-comment-emoji': 'online',

  'coach-team-strategy': 'community',
  'librarian-book-search': 'community',
  'neighbor-noise-apology': 'community',
  'bus-driver-question': 'community',

  // Overrides content id prefix-matching below: this legacy id happens to
  // start with the new 'sports' category's prefix word but predates that
  // category and belongs with the friend-category content instead.
  'sports-team-loss': 'friend',
}

// Newer content (added in bulk) uses a "<category>-slug" id convention, so
// its group can be read straight off the id prefix instead of needing a
// GROUP_OF entry per item. Legacy ids are checked first since a few of them
// (e.g. 'online-class-question-emoji') happen to start with another
// category's prefix word despite belonging elsewhere.
const ID_PREFIX_GROUPS: ConversationGroupKey[] = [
  'family',
  'teacher',
  'hospital',
  'store',
  'online',
  'community',
  'travel',
  'sports',
  'stranger',
]

export function groupOf(item: ConversationItem): ConversationGroupKey {
  if (item.id in GROUP_OF) return GROUP_OF[item.id]
  const prefix = item.id.split('-')[0] as ConversationGroupKey
  if (ID_PREFIX_GROUPS.includes(prefix)) return prefix
  return 'friend'
}

export function groupConversations(items: ConversationItem[]) {
  return GROUP_DEFS.map((def) => ({ def, items: items.filter((item) => groupOf(item) === def.key) })).filter(
    (g) => g.items.length > 0,
  )
}
