import type { Story } from './api'

export type StoryGroupKey = 'life' | 'proverb' | 'folktale'

export const GROUP_DEFS: { key: StoryGroupKey; label: string; emoji: string }[] = [
  { key: 'life', label: '생활 이야기', emoji: '🌼' },
  { key: 'proverb', label: '속담 이야기', emoji: '📜' },
  { key: 'folktale', label: '동화 이야기', emoji: '🏯' },
]

// Korean folktales and world classic fairy tales, retold as short
// comprehension passages (e.g. 흥부와 놀부, 인어공주).
const FOLKTALE_IDS = new Set([
  'heungbu-swallow-gourd',
  'kongjwi-lost-golden-shoe',
  'sun-moon-siblings-rope',
  'fairy-and-woodcutter',
  'snail-bride-secret',
  'golden-axe-silver-axe',
  'tiger-and-dried-persimmon',
  'porridge-granny-and-tiger',
  'goblin-magic-club',
  'magpie-repays-kindness',
  'donkey-ears-king-secret',
  'farting-daughter-in-law',
  'three-year-hill-tumble',
  'youth-spring-water',
  'lazybones-turned-ox',
  'brothers-share-rice-stacks',
  'ondal-and-pyeonggang-princess',
  'gyeonu-jiknyeo-magpie-bridge',
  'stingy-jarin-gobi',
  'magic-salt-millstone',
  'lump-old-man-goblin-song',
  'green-frog-always-disobeys',
  'five-talented-brothers',
  'turtle-and-rabbit-liver',
  'woodcutter-and-goblin-gold',
  'little-mermaid-sea-voice',
  'cinderella-glass-slipper',
  'snow-white-seven-dwarfs',
  'sleeping-beauty-spindle',
  'ugly-duckling-swan',
  'match-girl-cold-winter-night',
  'red-riding-hood-grandma-wolf',
  'hansel-gretel-candy-house',
  'rapunzel-tower-long-hair',
  'pinocchio-nose-grows-lying',
  'aladdin-magic-lamp-genie',
  'ant-and-grasshopper-winter',
  'rabbit-and-turtle-race',
  'three-little-pigs-houses',
  'shepherd-boy-cries-wolf',
  'fox-and-sour-grapes',
  'bremen-town-musicians',
  'golden-egg-goose-greed',
  'emperors-new-clothes',
  'thumbelina-tiny-princess',
  'wild-swans-eleven-princes',
  'jack-and-beanstalk-giant',
  'bluebird-of-happiness',
  'happy-prince-and-swallow',
  'wizard-of-oz-yellow-brick-road',

  'shim-cheong-lotus-flower',
  'toad-repays-favor-centipede',
  'fox-and-crane-dinner-invite',
  'wolf-and-seven-kids',
  'frog-prince-broken-promise',
  'lion-and-mouse-kindness',
  'peter-pan-neverland-adventure',
  'jungle-book-mowgli-friendship',
  'boy-who-bought-tree-shade',
  'fisherman-wife-three-wishes-greed',
  'peter-and-the-wolf-courage',
  'goblin-and-roasted-chestnut',
  'wise-daughter-in-law-riddles',
  'three-billy-goats-troll-bridge',
  'little-red-hen-hard-work',
  'stone-soup-village-sharing',
  'rumpelstiltskin-name-guess',
  'beauty-and-beast-kindness',
  'puss-in-boots-clever-cat',
  'snow-queen-gerda-friendship',
])

// Stories don't carry a content-type field of their own -- the three flavors
// (original everyday-life stories, stories built around teaching a Korean
// proverb, and folktale retellings) only show up in the title/plot itself,
// so each id is hand-assigned here. Anything not listed (including future
// admin-created items) falls back to the 'life' bucket below.
const PROVERB_IDS = new Set([
  'easy-quiz-surprise',
  'small-village-champion',
  'five-fingers-love',
  'short-kid-wrestling',
  'well-frog-trip',
  'bike-lock-forgotten',
  'talk-of-the-tiger',
  'group-project-chaos',
  'quick-fix-tape',
  'loud-empty-boast',
  'ten-tries-tree',
  'thank-you-letter-power',
  'seedling-talent',
  'neighbors-bigger-kite',
  'shipping-cost-more-than-gift',
  'one-well-focus',
  'tadpole-forgets',
  'dog-after-three-years',
  'ask-even-known-path',
  'beads-must-be-strung',
  'drink-kimchi-soup-first',
  'ash-on-finished-rice',
  'egg-against-rock',
  'acorn-height-comparing',
  'crab-eyes-south-wind',
  'thirsty-digs-well',
  'no-news-good-news',
  'jar-with-no-bottom',
  'seeing-is-believing',
  'wound-then-medicine',
  'fanning-burning-house',
  'ground-hardens-after-rain',
  'carpenter-blames-tools',
  'time-is-medicine',
  'sail-with-tailwind',
  'failure-mother-success',
  'word-choice-nuance',
  'crying-baby-gets-milk',
  'rivals-meet-narrow-bridge',
  'worm-wriggles-when-stepped',
  'first-spoonful-full',
  'follow-friend-blindly',
  'arm-bends-inward',
  'no-grave-without-excuse',
  'sky-falls-hole-appears',
  'hoe-turns-into-shovel',
  'flowing-water-never-rots',
  'market-day-coincidence',
  'bell-on-cat-neck',
  'painting-of-rice-cake',
  'illiterate-of-basics',
  'good-for-both-sides',
  'extra-rice-cake-for-hated-child',
  'small-bird-follows-stork',
  'blood-of-bird-leg',
  'ox-needs-hill',
  'covering-sky-with-palm',
  'watermelon-surface-lick',
  'no-smoke-without-fire',
  'quiet-cat-first-on-stove',
  'dont-eye-impossible-tree',
  'smiling-face-no-spit',
  'thousand-mile-first-step',
  'young-puppy-fears-nothing',

  'gymnastics-champion-misstep',
  'rainy-season-hope-returns',
  'field-trip-mishap-cascade',
  'missing-glasses-on-head',
  'classroom-gossip-overheard',
  'bike-brake-check-habit',
])

export function groupOf(story: Story): StoryGroupKey {
  if (story.groupKey && GROUP_DEFS.some((g) => g.key === story.groupKey)) {
    return story.groupKey as StoryGroupKey
  }
  if (FOLKTALE_IDS.has(story.id)) return 'folktale'
  if (PROVERB_IDS.has(story.id)) return 'proverb'
  return 'life'
}

export function groupStories(stories: Story[]) {
  return GROUP_DEFS.map((def) => ({ def, items: stories.filter((s) => groupOf(s) === def.key) })).filter(
    (g) => g.items.length > 0,
  )
}
